USE drae;

INSERT INTO palabra_multigenero (palabra, variante, diferencia) VALUES ('abejero', 'abejera','ra'),
	('ablanedo', 'ablanero','<!!special!!>'),
	('ablanedo', '<span > o ','<!!special!!>'),
	('abonador', 'abonadora','ra'),
	('acanto-', '-acanto','<!!special!!>'),
	('acanto-', '<span > o ','<!!special!!>'),
	('acedia', 'acedía','<!!special!!>'),
	('acedia', '<span > o ','<!!special!!>'),
	('aceitunero', 'aceitunera','ra'),
	('achichincle', 'achichinque','<!!special!!>'),
	('achichincle', 'achichintle','<!!special!!>'),
	('achichincle', '<span > o ','<!!special!!>'),
	('achichincle', '<span >, ','<!!special!!>'),
	('achiotero', 'achiotera','ra'),
	('acogido', 'acogida','da'),
	('acostado', 'acostada','da'),
	('acústico', 'acústica','ca'),
	('ademprio', 'ademprío','<!!special!!>'),
	('ademprio', '<span > o ','<!!special!!>'),
	('adnato', 'adnata','ta'),
	('aeróbic', 'aerobic','<!!special!!>'),
	('aeróbic', '<span > o ','<!!special!!>'),
	('aerodinámico', 'aerodinámica','ca'),
	('aeromancia', 'aeromancía','<!!special!!>'),
	('aeromancia', '<span > o ','<!!special!!>'),
	('aeronáutico', 'aeronáutica','ca'),
	('aerostato', 'aeróstato','<!!special!!>'),
	('aerostato', '<span > o ','<!!special!!>'),
	('afeitador', 'afeitadora','ra'),
	('afilador', 'afiladora','ra'),
	('áfilo', 'afilo','la'),
	('áfilo', '<span > o ','la'),
	('afirmativo', 'afirmativa','va'),
	('aforístico', 'aforística','ca'),
	('afrodisíaco', 'afrodisiaco','ca'),
	('afrodisíaco', '<span > o ','ca'),
	('agar-agar', 'agaragar','<!!special!!>'),
	('agar-agar', '<span > o ','<!!special!!>'),
	('agavillador', 'agavilladora','ra'),
	('agógico', 'agógica','ca'),
	('agracero', 'agracera','ra'),
	('agrafia', 'agrafía','<!!special!!>'),
	('agrafia', '<span > o ','<!!special!!>'),
	('aguadero', 'aguadera','ra'),
	('aguaucle', 'aguautle','<!!special!!>'),
	('aguaucle', '<span > o ','<!!special!!>'),
	('aguazul', 'aguazur','<!!special!!>'),
	('aguazul', '<span > o ','<!!special!!>'),
	('aguzadero', 'aguzadera','ra'),
	('aguzador', 'aguzadora','ra'),
	('ahogador', 'ahogadora','ra'),
	('ahorrativo', 'ahorrativa','va'),
	('ahuevado', 'ahuevada','da'),
	('ahumado', 'ahumada','da'),
	('alabastrino', 'alabastrina','na'),
	('alabastrita', 'alabastrites','<!!special!!>'),
	('alabastrita', '<span > o ','<!!special!!>'),
	('alacaluf', 'alacalufe','<!!special!!>'),
	('alacaluf', '<span > o ','<!!special!!>'),
	('alauda', 'alaude','<!!special!!>'),
	('alauda', '<span > o ','<!!special!!>'),
	('alavés', 'alavesa','sa'),
	('alazán', 'alazano','na'),
	('alazán', '<span > o ','na'),
	('albarizo', 'albariza','za'),
	('alcachofal', 'alcachofar','<!!special!!>'),
	('alcachofal', '<span > o ','<!!special!!>'),
	('alcachofero', 'alcachofera','ra'),
	('alcací', 'alcacil','<!!special!!>'),
	('alcací', '<span > o ','<!!special!!>'),
	('alcoholero', 'alcoholera','ra'),
	('aldeorrio', 'aldeorro','<!!special!!>'),
	('aldeorrio', '<span > o ','<!!special!!>'),
	('alectomancia', 'alectomancía','<!!special!!>'),
	('alectomancia', '<span > o ','<!!special!!>'),
	('alemán', 'alemana','na'),
	('alfoliero', 'alfolinero','<!!special!!>'),
	('alfoliero', '<span > o ','<!!special!!>'),
	('alfonsino', 'alfonsina','na'),
	('algodonoso', 'algodonosa','sa'),
	('aljarfa', 'aljarfe','<!!special!!>'),
	('aljarfa', '<span > o ','<!!special!!>'),
	('almarraja', 'almarraza','<!!special!!>'),
	('almarraja', '<span > o ','<!!special!!>'),
	('almendrado', 'almendrada','da'),
	('almizcleño', 'almizcleña','ña'),
	('almizclero', 'almizclera','ra'),
	('almocárabe', 'almocarbe','<!!special!!>'),
	('almocárabe', '<span > o ','<!!special!!>'),
	('almogavaría', 'almogavería','<!!special!!>'),
	('almogavaría', '<span > o ','<!!special!!>'),
	('almoháter', 'almohatre','<!!special!!>'),
	('almoháter', '<span > o ','<!!special!!>'),
	('almojarifadgo', 'almojarifalgo','<!!special!!>'),
	('almojarifadgo', '<span > o ','<!!special!!>'),
	('almojáter', 'almojatre','<!!special!!>'),
	('almojáter', '<span > o ','<!!special!!>'),
	('almoraduj', 'almoradux','<!!special!!>'),
	('almoraduj', '<span > o ','<!!special!!>'),
	('almotacenadgo', 'almotacenalgo','<!!special!!>'),
	('almotacenadgo', '<span > o ','<!!special!!>'),
	('almotazaf', 'almotazán','<!!special!!>'),
	('almotazaf', '<span > o ','<!!special!!>'),
	('almozala', 'almozalla','<!!special!!>'),
	('almozala', '<span > o ','<!!special!!>'),
	('almudí', 'almudín','<!!special!!>'),
	('almudí', '<span > o ','<!!special!!>'),
	('almuzala', 'almuzalla','<!!special!!>'),
	('almuzala', '<span > o ','<!!special!!>'),
	('áloe', 'aloe','<!!special!!>'),
	('áloe', '<span > o ','<!!special!!>'),
	('alpende', 'alpendre','<!!special!!>'),
	('alpende', '<span > o ','<!!special!!>'),
	('alpistela', 'alpistera','<!!special!!>'),
	('alpistela', '<span > o ','<!!special!!>'),
	('alquicel', 'alquicer','<!!special!!>'),
	('alquicel', '<span > o ','<!!special!!>'),
	('altivez', 'altiveza','<!!special!!>'),
	('altivez', '<span > o ','<!!special!!>'),
	('alvéolo', 'alveolo','<!!special!!>'),
	('alvéolo', '<span > o ','<!!special!!>'),
	('alzacuello', 'alzacuellos','<!!special!!>'),
	('alzacuello', '<span > o ','<!!special!!>'),
	('alzador', 'alzadora','ra'),
	('amalecita', 'amalequita','<!!special!!>'),
	('amalecita', '<span > o ','<!!special!!>'),
	('amancay', 'amancaya','<!!special!!>'),
	('amancay', 'amancayo','<!!special!!>'),
	('amancay', '<span > o ','<!!special!!>'),
	('amancay', '<span >, ','<!!special!!>'),
	('amanecido', 'amanecida','da'),
	('amansador', 'amansadora','ra'),
	('amasador', 'amasadora','ra'),
	('ambarino', 'ambarina','na'),
	('ambidextro', 'ambidiestro','tra'),
	('ambidextro', '<span > o ','tra'),
	('ambuesta', 'ambueza','<!!special!!>'),
	('ambuesta', '<span > o ','<!!special!!>'),
	('ametrallador', 'ametralladora','ra'),
	('amoniaco', 'amoníaco','<!!special!!>'),
	('amoniaco', '<span > o ','<!!special!!>'),
	('ampliador', 'ampliadora','ra'),
	('anacardino', 'anacardina','na'),
	('anafalla', 'anafaya','<!!special!!>'),
	('anafalla', '<span > o ','<!!special!!>'),
	('anafrodisíaco', 'anafrodisiaco','ca'),
	('anafrodisíaco', '<span > o ','ca'),
	('anahuaca', 'anahuacense','<!!special!!>'),
	('anahuaca', '<span > o ','<!!special!!>'),
	('andadero', 'andadera','ra'),
	('andoba', 'andóbal','<!!special!!>'),
	('andoba', '<span > o ','<!!special!!>'),
	('anémona', 'anemona','<!!special!!>'),
	('anémona', '<span > o ','<!!special!!>'),
	('anglístico', 'anglística','ca'),
	('anhídrido', 'anhidrido','da'),
	('anhídrido', '<span > o ','da'),
	('ansimesmo', 'ansimismo','<!!special!!>'),
	('ansimesmo', '<span > o ','<!!special!!>'),
	('antiafrodisíaco', 'antiafrodisiaco','ca'),
	('antiafrodisíaco', '<span > o ','ca'),
	('antuviado', 'antuviada','da'),
	('apaste', 'apastle','<!!special!!>'),
	('apaste', '<span > o ','<!!special!!>'),
	('apipisca', 'apipizca','<!!special!!>'),
	('apipisca', '<span > o ','<!!special!!>'),
	('aplanador', 'aplanadora','ra'),
	('apologético', 'apologética','ca'),
	('apolónida', 'apolonida','<!!special!!>'),
	('apolónida', '<span > o ','<!!special!!>'),
	('apopléjico', 'apoplético','ca'),
	('apopléjico', '<span > o ','ca'),
	('apretadero', 'apretadera','ra'),
	('archivístico', 'archivística','ca'),
	('arenisco', 'arenisca','ca'),
	('areola', 'aréola','<!!special!!>'),
	('areola', '<span > o ','<!!special!!>'),
	('argentado', 'argentada','da'),
	('argüendero', 'argüendera','ra'),
	('arismético', 'arismética','ca'),
	('aritmético', 'aritmética','ca'),
	('armoniaco', 'armoníaco','<!!special!!>'),
	('armoniaco', '<span > o ','<!!special!!>'),
	('arrancador', 'arrancadora','ra'),
	('arreado', 'arreada','da'),
	('arrocero', 'arrocera','ra'),
	('ascético', 'ascética','ca'),
	('aserrador', 'aserradora','ra'),
	('asoleado', 'asoleada','da'),
	('áspid', 'áspide','<!!special!!>'),
	('aspirador', 'aspiradora','ra'),
	('asunceno', 'asunceño','ña'),
	('asunceno', '<span > o ','na'),
	('atríaca', 'atriaca','<!!special!!>'),
	('atríaca', '<span > o ','<!!special!!>'),
	('atunero', 'atunera','ra'),
	('austriaco', 'austríaco','ca'),
	('austriaco', '<span > o ','ca'),
	('autocrítico', 'autocrítica','ca'),
	('avellanero', 'avellanera','ra'),
	('axiomático', 'axiomática','ca'),
	('azotado', 'azotada','da'),
	('azucarero', 'azucarera','ra'),
	('azufrero', 'azufrera','ra'),
	('azulón', 'azulona','na'),
	('bacinica', 'bacinilla','<!!special!!>'),
	('bacinica', '<span > o ','<!!special!!>'),
	('bagual', 'baguala','la'),
	('bailarín', 'bailarina','na'),
	('bajero', 'bajera','ra'),
	('bajines', 'bajini','<!!special!!>'),
	('bajines', 'bajinis','<!!special!!>'),
	('bajines', '<span > o ','<!!special!!>'),
	('bajines', '<span >, ','<!!special!!>'),
	('bálano', 'balano','<!!special!!>'),
	('bálano', '<span > o ','<!!special!!>'),
	('balaustrado', 'balaustrada','da'),
	('balaustre', 'balaústre','<!!special!!>'),
	('balaustre', '<span > o ','<!!special!!>'),
	('baldaquín', 'baldaquino','<!!special!!>'),
	('baldaquín', '<span > o ','<!!special!!>'),
	('ballenero', 'ballenera','ra'),
	('bambú', 'bambuc','<!!special!!>'),
	('bambú', '<span > o ','<!!special!!>'),
	('bañero', 'bañera','ra'),
	('baro-', '-baro','ra'),
	('baro-', '<span > o ','ra'),
	('barquillero', 'barquillera','ra'),
	('barredero', 'barredera','ra'),
	('barreño', 'barreña','ña'),
	('bastonero', 'bastonera','ra'),
	('batidor', 'batidora','ra'),
	('bávaro', 'bávara','ra'),
	('bayonés', 'bayonesa','sa'),
	('bearnés', 'bearnesa','sa'),
	('bebedero', 'bebedera','ra'),
	('bebido', 'bebida','da'),
	('becqueriano', 'becqueriana','na'),
	('bellotero', 'bellotera','ra'),
	('bencinero', 'bencinera','ra'),
	('benemérito', 'benemérita','ta'),
	('bérbero', 'bérberos','<!!special!!>'),
	('bérbero', '<span > o ','<!!special!!>'),
	('bereber', 'beréber','<!!special!!>'),
	('bereber', '<span > o ','<!!special!!>'),
	('besamel', 'besamela','<!!special!!>'),
	('besamel', '<span > o ','<!!special!!>'),
	('betume', 'betumen','<!!special!!>'),
	('betume', '<span > o ','<!!special!!>'),
	('bibliomancia', 'bibliomancía','<!!special!!>');

INSERT INTO palabra_multigenero (palabra, variante, diferencia) VALUES ('bibliomancia', '<span > o ','<!!special!!>'),
	('bienvenido', 'bienvenida','da'),
	('billetero', 'billetera','ra'),
	('bimano', 'bímano','na'),
	('bimano', '<span > o ','na'),
	('bio-', '-bio','<!!special!!>'),
	('biofísico', 'biofísica','ca'),
	('biomecánico', 'biomecánica','ca'),
	('bio-', '<span > o ','<!!special!!>'),
	('biruje', 'biruji','<!!special!!>'),
	('biruje', '<span > o ','<!!special!!>'),
	('bisayo', 'bisaya','ya'),
	('bisector', 'bisectriz','triz'),
	('bla-bla-bla', 'blablablá','<!!special!!>'),
	('bla-bla-bla', '<span > o ','<!!special!!>'),
	('blanquillo', 'blanquilla','lla'),
	('bocaza', 'bocazas','<!!special!!>'),
	('bocaza', '<span > o ','<!!special!!>'),
	('boleado', 'boleada','da'),
	('boloñés', 'boloñesa','sa'),
	('bombeta', 'bombetas','<!!special!!>'),
	('bombeta', '<span > o ','<!!special!!>'),
	('bonitero', 'bonitera','ra'),
	('boratero', 'boratera','ra'),
	('borbotar', 'borbotear','<!!special!!>'),
	('borbotar', '<span > o ','<!!special!!>'),
	('borcelano', 'borcelana','na'),
	('bordelés', 'bordelesa','sa'),
	('bosniaco', 'bosníaco','ca'),
	('bosniaco', '<span > o ','ca'),
	('bosquimán', 'bosquimano','<!!special!!>'),
	('bosquimán', '<span > o ','<!!special!!>'),
	('botasilla', 'botasillas','<!!special!!>'),
	('botasilla', '<span > o ','<!!special!!>'),
	('breñal', 'breñar','<!!special!!>'),
	('breñal', '<span > o ','<!!special!!>'),
	('briago', 'briaga','ga'),
	('bribri', 'bribrí','<!!special!!>'),
	('bribri', '<span > o ','<!!special!!>'),
	('briofito', 'briófito','ta'),
	('briofito', '<span > o ','ta'),
	('bronquiolo', 'bronquíolo','<!!special!!>'),
	('bronquiolo', '<span > o ','<!!special!!>'),
	('bucare', 'búcare','<!!special!!>'),
	('bucare', '<span > o ','<!!special!!>'),
	('bue', 'bué','<!!special!!>'),
	('bue', '<span > o ','<!!special!!>'),
	('buganvilia', 'buganvilla','<!!special!!>'),
	('buganvilia', '<span > o ','<!!special!!>'),
	('buitrero', 'buitrera','ra'),
	('bumbulín', 'bumbulón','<!!special!!>'),
	('bumbulín', '<span > o ','<!!special!!>'),
	('buñuelero', 'buñuelera','ra'),
	('buscabulla', 'buscabullas','<!!special!!>'),
	('buscabulla', '<span > o ','<!!special!!>'),
	('bustrófedon', 'bustrofedon','<!!special!!>'),
	('bustrófedon', '<span > o ','<!!special!!>'),
	('bute', 'buten','<!!special!!>'),
	('bute', '<span > o ','<!!special!!>'),
	('cabecero', 'cabecera','ra'),
	('cabido', 'cabida','da'),
	('cabrerizo', 'cabreriza','za'),
	('cabruno', 'cabruna','na'),
	('cacahuacentli', 'cacahuacintle','<!!special!!>'),
	('cacahuacentli', '<span > o ','<!!special!!>'),
	('cacán', 'cacana','<!!special!!>'),
	('cacán', '<span > o ','<!!special!!>'),
	('cachimbeado', 'cachimbeada','da'),
	('caganido', 'caganidos','<!!special!!>'),
	('caganido', '<span > o ','<!!special!!>'),
	('cagatinta', 'cagatintas','<!!special!!>'),
	('cagatinta', '<span > o ','<!!special!!>'),
	('caído', 'caída','da'),
	('calabacero', 'calabacera','ra'),
	('calador', 'caladora','ra'),
	('calcedonio', 'calcedonia','nia'),
	('calculador', 'calculadora','ra'),
	('caldudo', 'calduda','da'),
	('calizo', 'caliza','za'),
	('camarina', 'camariña','<!!special!!>'),
	('camarina', '<span > o ','<!!special!!>'),
	('camaronero', 'camaronera','ra'),
	('cámpago', 'campago','<!!special!!>'),
	('cámpago', '<span > o ','<!!special!!>'),
	('canastero', 'canastera','ra'),
	('cancín', 'cancina','na'),
	('candongo', 'candonga','ga'),
	('canelado', 'canelada','da'),
	('cangrejero', 'cangrejera','ra'),
	('canillero', 'canillera','ra'),
	('cantiga', 'cántiga','<!!special!!>'),
	('cantiga', '<span > o ','<!!special!!>'),
	('cantonero', 'cantonera','ra'),
	('cantor', 'cantora','ra'),
	('capirotado', 'capirotada','da'),
	('capnomancia', 'capnomancía','<!!special!!>'),
	('capnomancia', '<span > o ','<!!special!!>'),
	('capotero', 'capotera','ra'),
	('caracha', 'carache','<!!special!!>'),
	('caracha', '<span > o ','<!!special!!>'),
	('carau', 'caraú','<!!special!!>'),
	('carau', '<span > o ','<!!special!!>'),
	('cardiaca', 'cardíaca','<!!special!!>'),
	('cardiaca', '<span > o ','<!!special!!>'),
	('cardiaco', 'cardíaco','ca'),
	('cardiaco', '<span > o ','ca'),
	('cardio-', '-cardio','<!!special!!>'),
	('cardio-', '<span > o ','<!!special!!>'),
	('careto', 'careta','ta'),
	('carrasposo', 'carrasposa','sa'),
	('cartel', 'cártel','<!!special!!>'),
	('cartelero', 'cartelera','ra'),
	('cartel', '<span > o ','<!!special!!>'),
	('cartomancia', 'cartomancía','<!!special!!>'),
	('cartomancia', '<span > o ','<!!special!!>'),
	('castellano-leonés', 'castellanoleonés','sa'),
	('castellano-leonés', '<span > o ','sa'),
	('castellano-manchego', 'castellanomanchego','ga'),
	('castellano-manchego', '<span > o ','ga'),
	('castrapuercas', 'castrapuercos','<!!special!!>'),
	('castrapuercas', '<span > o ','<!!special!!>'),
	('casuístico', 'casuística','ca'),
	('catabre', 'catabro','<!!special!!>'),
	('catabre', '<span > o ','<!!special!!>'),
	('catapum', 'catapún','<!!special!!>'),
	('catapum', '<span > o ','<!!special!!>'),
	('catenario', 'catenaria','ria'),
	('caterético', 'caterética','ca'),
	('catóptrico', 'catóptrica','ca'),
	('catoptromancia', 'catoptromancía','<!!special!!>'),
	('catoptromancia', '<span > o ','<!!special!!>'),
	('catorceno', 'catorcena','na'),
	('cauchero', 'cauchera','ra'),
	('caudimano', 'caudímano','<!!special!!>'),
	('caudimano', '<span > o ','<!!special!!>'),
	('causídico', 'causídica','ca'),
	('cayagual', 'cayahual','<!!special!!>'),
	('cayagual', '<span > o ','<!!special!!>'),
	('cazador', 'cazadora','ra'),
	('cefálico', 'cefálica','ca'),
	('celíaco', 'celíaca','ca'),
	('celíaco', 'celiaco','ca'),
	('celíaco', '<span > o ','ca'),
	('celtíbero', 'celtíbera','ra'),
	('celtíbero', 'celtibero','--'),
	('cencellada', 'cenceñada','<!!special!!>'),
	('cencellada', '<span > o ','<!!special!!>'),
	('cenit', 'cénit','<!!special!!>'),
	('cenit', '<span > o ','<!!special!!>'),
	('centimano', 'centímano','<!!special!!>'),
	('centimano', '<span > o ','<!!special!!>'),
	('centrifugador', 'centrifugadora','ra'),
	('cerámico', 'cerámica','ca'),
	('cerasta', 'cerastas','<!!special!!>'),
	('cerasta', '<span > o ','<!!special!!>'),
	('ceraunomancia', 'ceraunomancía','<!!special!!>'),
	('ceraunomancia', '<span > o ','<!!special!!>'),
	('cerillero', 'cerillera','ra'),
	('ceromancia', 'ceromancía','<!!special!!>'),
	('ceromancia', '<span > o ','<!!special!!>'),
	('cerradero', 'cerradera','ra'),
	('certificatorio', 'certificatoria','ria'),
	('chachaguato', 'chachaguata','ta'),
	('chambergo', 'chamberga','ga'),
	('chamicero', 'chamicera','ra'),
	('chapeador', 'chapeadora','ra'),
	('chibolo', 'chibola','la'),
	('chichicaste', 'chichicastle','<!!special!!>'),
	('chichicaste', '<span > o ','<!!special!!>'),
	('chiquigüite', 'chiquihuite','<!!special!!>'),
	('chiquigüite', '<span > o ','<!!special!!>'),
	('chiringo', 'chiringa','ga'),
	('chirusa', 'chiruza','<!!special!!>'),
	('chirusa', '<span > o ','<!!special!!>'),
	('chivado', 'chivada','da'),
	('chivero', 'chivera','<!!special!!>'),
	('chofer', 'chófer','<!!special!!>'),
	('chofer', '<span > o ','<!!special!!>'),
	('chorreado', 'chorreada','da'),
	('chungo', 'chunga','ga'),
	('chupa-chup', 'chupa-chups','<!!special!!>'),
	('chupa-chup', 'chupachús','<!!special!!>'),
	('chupa-chup', '<span > o ','<!!special!!>'),
	('chupa-chup', '<span >, ','<!!special!!>'),
	('chupamedia', 'chupamedias','<!!special!!>'),
	('chupamedia', '<span > o ','<!!special!!>'),
	('ciático', 'ciática','ca'),
	('ciclostil', 'ciclostilo','<!!special!!>'),
	('ciclostil', '<span > o ','<!!special!!>'),
	('cinegético', 'cinegética','ca'),
	('cinemático', 'cinemática','ca'),
	('cinerario', 'cineraria','ria'),
	('cinético', 'cinética','ca'),
	('cinqueno', 'cinquena','na'),
	('cito-', '-cito','<!!special!!>'),
	('cito-', '<span > o ','<!!special!!>'),
	('clarificador', 'clarificadora','ra'),
	('cleptomaníaco', 'cleptomaniaco','ca'),
	('cleptomaníaco', '<span > o ','ca'),
	('cocoroco', 'cocoroca','ca'),
	('cóctel', 'coctel','<!!special!!>'),
	('cóctel', '<span > o ','<!!special!!>'),
	('cogedero', 'cogedera','ra'),
	('cogido', 'cogida','da'),
	('cojinoba', 'cojinova','<!!special!!>'),
	('cojinoba', '<span > o ','<!!special!!>'),
	('combinatorio', 'combinatoria','ria'),
	('comelón', 'comelona','na'),
	('comilón', 'comilona','na'),
	('computador', 'computadora','ra'),
	('conejero', 'conejera','ra'),
	('conejuno', 'conejuna','na'),
	('cónico', 'cónica','ca'),
	('consumido', 'consumida','da'),
	('contradictorio', 'contradictoria','ria'),
	('convidado', 'convidada','da'),
	('convocatorio', 'convocatoria','ria'),
	('copetón', 'copetona','na'),
	('copetudo', 'copetuda','da'),
	('copiador', 'copiadora','ra'),
	('coralino', 'coralina','na'),
	('corchero', 'corchera','ra'),
	('corderino', 'corderina','na'),
	('cordiaco', 'cordíaco','ca'),
	('cordiaco', '<span > o ','ca'),
	('coronario', 'coronaria','ria'),
	('corralero', 'corralera','ra'),
	('corredero', 'corredera','ra'),
	('corroncho', 'corroncha','cha'),
	('cortafuego', 'cortafuegos','<!!special!!>'),
	('cortafuego', '<span > o ','<!!special!!>'),
	('cosechador', 'cosechadora','ra'),
	('cosmético', 'cosmética','ca'),
	('cosoria', 'cosoriola','<!!special!!>'),
	('cosoria', '<span > o ','<!!special!!>'),
	('costero', 'costera','ra'),
	('cracoviano', 'cracoviana','na'),
	('crematístico', 'crematística','ca'),
	('cuadrumano', 'cuadrúmano','na'),
	('cuadrumano', '<span > o ','na'),
	('cubrecabeza', 'cubrecabezas','<!!special!!>'),
	('cubrecabeza', '<span > o ','<!!special!!>'),
	('cucarachero', 'cucarachera','ra'),
	('cuculmeque', 'cuculmeca','ca'),
	('cudrío', 'cudría','a'),
	('cuentístico', 'cuentística','ca'),
	('culero', 'culera','ra'),
	('culinario', 'culinaria','ria'),
	('curativo', 'curativa','va');

INSERT INTO palabra_multigenero (palabra, variante, diferencia) VALUES ('currutaco', 'currutaca','ca'),
	('dactilo-', '-dáctilo','<!!special!!>'),
	('dactilo-', '<span > o ','<!!special!!>'),
	('damasceno', 'damascena','na'),
	('declaratorio', 'declaratoria','ria'),
	('dedicatorio', 'dedicatoria','ria'),
	('defensivo', 'defensiva','va'),
	('defeso', 'defesa','sa'),
	('deixis', 'deíxis','<!!special!!>'),
	('deixis', '<span > o ','<!!special!!>'),
	('delantero', 'delantera','ra'),
	('demoníaco', 'demoniaco','ca'),
	('demoníaco', '<span > o ','ca'),
	('demonomancia', 'demonomancía','<!!special!!>'),
	('demonomancia', '<span > o ','<!!special!!>'),
	('dentellado', 'dentellada','da'),
	('depurador', 'depuradora','ra'),
	('derechero', 'derechera','ra'),
	('derivado', 'derivada','da'),
	('dermo-', '-dermo','<!!special!!>'),
	('dermo-', '<span > o ','<!!special!!>'),
	('desalinizador', 'desalinizadora','ra'),
	('descangallar', 'descangayar','<!!special!!>'),
	('descangallar', '<span > o ','<!!special!!>'),
	('desfibrador', 'desfibradora','ra'),
	('desgarreate', 'desgarriate','<!!special!!>'),
	('desgarreate', '<span > o ','<!!special!!>'),
	('desgranador', 'desgranadora','ra'),
	('deshuesador', 'deshuesadora','ra'),
	('desmentido', 'desmentida','da'),
	('desmotador', 'desmotadora','ra'),
	('despernado', 'despernada','da'),
	('despiporre', 'despiporren','<!!special!!>'),
	('despiporre', '<span > o ','<!!special!!>'),
	('despistado', 'despistada','da'),
	('destrozón', 'destrozona','na'),
	('detrito', 'detritus','<!!special!!>'),
	('detrito', '<span > o ','<!!special!!>'),
	('dietético', 'dietética','ca'),
	('difusor', 'difusora','ra'),
	('dihueñe', 'dihueñi','<!!special!!>'),
	('dihueñe', '<span > o ','<!!special!!>'),
	('dilatorio', 'dilatoria','ria'),
	('dinámico', 'dinámica','ca'),
	('dinamo', 'dínamo','<!!special!!>'),
	('dinamo', '<span > o ','<!!special!!>'),
	('dionisíaco', 'dionisiaco','ca'),
	('dionisíaco', '<span > o ','ca'),
	('dióptrico', 'dióptrica','ca'),
	('diplomático', 'diplomática','ca'),
	('dipsomaníaco', 'dipsomaniaco','ca'),
	('dipsomaníaco', '<span > o ','ca'),
	('directivo', 'directiva','va'),
	('disgrafia', 'disgrafía','<!!special!!>'),
	('disgrafia', '<span > o ','<!!special!!>'),
	('distribuidor', 'distribuidora','ra'),
	('docimástico', 'docimástica','ca'),
	('domínica', 'dominica','<!!special!!>'),
	('domínica', '<span > o ','<!!special!!>'),
	('dormidero', 'dormidera','ra'),
	('dormilón', 'dormilona','na'),
	('eborario', 'eboraria','ria'),
	('ecdótico', 'ecdótica','ca'),
	('egilope', 'egílope','<!!special!!>'),
	('egilope', '<span > o ','<!!special!!>'),
	('egipciaco', 'egipcíaco','ca'),
	('egipciaco', '<span > o ','ca'),
	('electroacústico', 'electroacústica','ca'),
	('electrodinámico', 'electrodinámica','ca'),
	('electrolisis', 'electrólisis','<!!special!!>'),
	('electrolisis', '<span > o ','<!!special!!>'),
	('electrolito', 'electrólito','<!!special!!>'),
	('electrolito', '<span > o ','<!!special!!>'),
	('electromecánico', 'electromecánica','ca'),
	('electrónico', 'electrónica','ca'),
	('electroquímico', 'electroquímica','ca'),
	('electrostático', 'electrostática','ca'),
	('elefancíaco', 'elefanciaco','ca'),
	('elefancíaco', '<span > o ','ca'),
	('elefancia', 'elefancía','<!!special!!>'),
	('elefancia', '<span > o ','<!!special!!>'),
	('elegíaco', 'elegiaco','ca'),
	('elegíaco', '<span > o ','ca'),
	('elevador', 'elevadora','ra'),
	('eliminatorio', 'eliminatoria','ria'),
	('élite', 'elite','<!!special!!>'),
	('élite', '<span > o ','<!!special!!>'),
	('elixir', 'elíxir','<!!special!!>'),
	('elixir', '<span > o ','<!!special!!>'),
	('embotellador', 'embotelladora','ra'),
	('emisor', 'emisora','ra'),
	('empacador', 'empacadora','ra'),
	('empavesado', 'empavesada','da'),
	('encerador', 'enceradora','ra'),
	('encimero', 'encimera','ra'),
	('encolador', 'encoladora','ra'),
	('encorchador', 'encorchadora','ra'),
	('energético', 'energética','ca'),
	('engañamundo', 'engañamundos','<!!special!!>'),
	('engañamundo', '<span > o ','<!!special!!>'),
	('ensabanado', 'ensabanada','da'),
	('ensayístico', 'ensayística','ca'),
	('ensenado', 'ensenada','da'),
	('ensillado', 'ensillada','da'),
	('erótico', 'erótica','ca'),
	('escalado', 'escalada','da'),
	('escaldado', 'escaldada','da'),
	('escampado', 'escampada','da'),
	('escapado', 'escapada','da'),
	('escarchado', 'escarchada','da'),
	('esclerótico', 'esclerótica','ca'),
	('escobero', 'escobera','ra'),
	('escombrero', 'escombrera','ra'),
	('escuincle', 'escuintle','tla'),
	('escuincle', '<span > o ','cla'),
	('esfácelo', 'esfacelo','<!!special!!>'),
	('esfácelo', '<span > o ','<!!special!!>'),
	('espadado', 'espadada','da'),
	('espagírico', 'espagírica','ca'),
	('españolado', 'españolada','da'),
	('esparraguero', 'esparraguera','ra'),
	('espatulomancia', 'espatulomancía','<!!special!!>'),
	('espatulomancia', '<span > o ','<!!special!!>'),
	('espetaperro', 'espetaperros','<!!special!!>'),
	('espetaperro', '<span > o ','<!!special!!>'),
	('espigador', 'espigadora','ra'),
	('esporófito', 'esporofito','<!!special!!>'),
	('esporófito', '<span > o ','<!!special!!>'),
	('esquilador', 'esquiladora','ra'),
	('esquinero', 'esquinera','ra'),
	('ester', 'éster','<!!special!!>'),
	('ester', '<span > o ','<!!special!!>'),
	('estilístico', 'estilística','ca'),
	('estilográfico', 'estilográfica','ca'),
	('estimativo', 'estimativa','va'),
	('estocástico', 'estocástica','ca'),
	('estrujador', 'estrujadora','ra'),
	('estudiantino', 'estudiantina','na'),
	('evasivo', 'evasiva','va'),
	('ex cáthedra', 'ex cátedra','<!!special!!>'),
	('ex cáthedra', '<span > o ','<!!special!!>'),
	('excavador', 'excavadora','ra'),
	('exegesis', 'exégesis','<!!special!!>'),
	('exegesis', '<span > o ','<!!special!!>'),
	('exegeta', 'exégeta','<!!special!!>'),
	('exegeta', '<span > o ','<!!special!!>'),
	('exoftalmia', 'exoftalmía','<!!special!!>'),
	('exoftalmia', '<span > o ','<!!special!!>'),
	('exósmosis', 'exosmosis','<!!special!!>'),
	('exósmosis', '<span > o ','<!!special!!>'),
	('extractor', 'extractora','ra'),
	('extrusor', 'extrusora','ra'),
	('fabulístico', 'fabulística','ca'),
	('fago-', '‒́fago','ga'),
	('fago-', '<span > o ','ga'),
	('fagot', 'fagote','<!!special!!>'),
	('fagot', '<span > o ','<!!special!!>'),
	('fajado', 'fajada','da'),
	('falcado', 'falcada','da'),
	('fangal', 'fangar','<!!special!!>'),
	('fangal', '<span > o ','<!!special!!>'),
	('farandola', 'farándola','<!!special!!>'),
	('farandola', '<span > o ','<!!special!!>'),
	('farmacocinético', 'farmacocinética','ca'),
	('farruco', 'farruca','ca'),
	('fastidiado', 'fastidiada','da'),
	('fatamorgana', 'fata morgana','<!!special!!>'),
	('fatamorgana', '<span > o ','<!!special!!>'),
	('feladiz', 'felariz','<!!special!!>'),
	('feladiz', '<span > o ','<!!special!!>'),
	('figulino', 'figulina','na'),
	('filarmónico', 'filarmónica','ca'),
	('filmador', 'filmadora','ra'),
	('filo-', '‒́filo','la'),
	('filo-', '<span > o ','la'),
	('finoúgrio', 'fino-ugrio','gria'),
	('finoúgrio', '<span > o ','gria'),
	('fisicoquímico', 'fisicoquímica','ca'),
	('fisiognómico', 'fisiognómica','ca'),
	('fito-', '-fito','ta'),
	('fito-', '<span > o ','ta'),
	('folíolo', 'foliolo','<!!special!!>'),
	('folíolo', '<span > o ','<!!special!!>'),
	('fonemático', 'fonemática','ca'),
	('fonético', 'fonética','ca'),
	('fono-', '‒́fono','na'),
	('fonomímico', 'fonomímica','ca'),
	('fono-', '<span > o ','na'),
	('forrajero', 'forrajera','ra'),
	('fosco', 'fosca','ca'),
	('fosforero', 'fosforera','ra'),
	('fotocopiador', 'fotocopiadora','ra'),
	('fotograbador', 'fotograbadora','ra'),
	('fotolisis', 'fotólisis','<!!special!!>'),
	('fotolisis', '<span > o ','<!!special!!>'),
	('fotomecánico', 'fotomecánica','ca'),
	('fotoquímico', 'fotoquímica','ca'),
	('foxtrot', 'fox-trot','<!!special!!>'),
	('foxtrot', '<span > o ','<!!special!!>'),
	('franjar', 'franjear','<!!special!!>'),
	('franjar', '<span > o ','<!!special!!>'),
	('fregón', 'fregona','na'),
	('freidor', 'freidora','ra'),
	('frejón', 'fréjul','<!!special!!>'),
	('frejón', '<span > o ','<!!special!!>'),
	('fresero', 'fresera','ra'),
	('friolero', 'friolera','ra'),
	('frontalero', 'frontalera','ra'),
	('funerario', 'funeraria','ria'),
	('fútbol', 'futbol','<!!special!!>'),
	('fútbol', '<span > o ','<!!special!!>'),
	('galaicoportugués', 'galaico-portugués','sa'),
	('galaicoportugués', '<span > o ','sa'),
	('galgo', 'galga','ga'),
	('galileo', 'galilea','<!!special!!>'),
	('gallegoportugués', 'gallego-portugués','sa'),
	('gallegoportugués', '<span > o ','sa'),
	('galvanoplástico', 'galvanoplástica','ca'),
	('gambuj', 'gambujo','<!!special!!>'),
	('gambuj', '<span > o ','<!!special!!>'),
	('gametófito', 'gametofito','<!!special!!>'),
	('gametófito', '<span > o ','<!!special!!>'),
	('gamo-', '‒́gamo','ma'),
	('gamo-', '<span > o ','ma'),
	('garguero', 'gargüero','<!!special!!>'),
	('garguero', '<span > o ','<!!special!!>'),
	('garrapiñado', 'garrapiñada','da'),
	('garrotero', 'garrotera','ra'),
	('gaseoso', 'gaseosa','sa'),
	('genesíaco', 'genesiaco','ca'),
	('genesíaco', '<span > o ','ca'),
	('genético', 'genética','ca'),
	('genetlíaca', 'genetliaca','<!!special!!>'),
	('genetlíaca', '<span > o ','<!!special!!>'),
	('genetlíaco', 'genetliaca','<!!special!!>'),
	('genetlíaco', 'genetlíaca','<!!special!!>'),
	('genetlíaco', 'genetliaco','<!!special!!>'),
	('genetlíaco', '<span > o ','<!!special!!>'),
	('geobotánico', 'geobotánica','ca'),
	('geofísico', 'geofísica','ca'),
	('geomancia', 'geomancía','<!!special!!>'),
	('geomancia', '<span > o ','<!!special!!>'),
	('geoquímico', 'geoquímica','ca'),
	('geotécnico', 'geotécnica','ca'),
	('gerente', 'gerenta','<!!special!!>'),
	('giganteo', 'gigantea','a'),
	('gillete', 'gillette','<!!special!!>'),
	('gillete', '<span > o ','<!!special!!>'),
	('gimnástico', 'gimnástica','ca');

INSERT INTO palabra_multigenero (palabra, variante, diferencia) VALUES ('giratorio', 'giratoria','ria'),
	('giróstato', 'girostato','<!!special!!>'),
	('giróstato', '<span > o ','<!!special!!>'),
	('gladíolo', 'gladiolo','<!!special!!>'),
	('gladíolo', '<span > o ','<!!special!!>'),
	('gnomónico', 'gnomónica','ca'),
	('gorbiz', 'gorbizo','<!!special!!>'),
	('gorbiz', '<span > o ','<!!special!!>'),
	('grabador', 'grabadora','ra'),
	('gradíolo', 'gradiolo','<!!special!!>'),
	('gradíolo', '<span > o ','<!!special!!>'),
	('grafila', 'gráfila','<!!special!!>'),
	('grafila', '<span > o ','<!!special!!>'),
	('granadino', 'granadina','na'),
	('granillero', 'granillera','ra'),
	('granizado', 'granizada','da'),
	('granujado', 'granujada','da'),
	('grátil', 'gratil','<!!special!!>'),
	('grátil', '<span > o ','<!!special!!>'),
	('greguescos', 'gregüescos','<!!special!!>'),
	('greguescos', '<span > o ','<!!special!!>'),
	('guadamací', 'guadamacil','<!!special!!>'),
	('guadamací', '<span > o ','<!!special!!>'),
	('guadañador', 'guadañadora','ra'),
	('guajiro', 'guajira','ra'),
	('guanero', 'guanera','ra'),
	('guantanamero', 'guantanamera','ra'),
	('guardabosque', 'guardabosques','<!!special!!>'),
	('guardabosque', '<span > o ','<!!special!!>'),
	('guardapolvo', 'guardapolvos','<!!special!!>'),
	('guardapolvo', '<span > o ','<!!special!!>'),
	('guayabero', 'guayabera','ra'),
	('guion', 'guión','<!!special!!>'),
	('guion', '<span > o ','<!!special!!>'),
	('gurbio', 'gurbia','bia'),
	('gurrumino', 'gurrumina','na'),
	('habanero', 'habanera','ra'),
	('hadado', 'hadada','da'),
	('haikai', 'hai-kai','<!!special!!>'),
	('haikai', '<span > o ','<!!special!!>'),
	('haiku', 'haikú','<!!special!!>'),
	('haiku', '<span > o ','<!!special!!>'),
	('hallado', 'hallada','da'),
	('hamadría', 'hamadriada','<!!special!!>'),
	('hamadría', '<span > o ','<!!special!!>'),
	('héctico', 'héctica','ca'),
	('hedentino', 'hedentina','na'),
	('helespontíaco', 'helespontiaco','ca'),
	('helespontíaco', '<span > o ','ca'),
	('helíaco', 'heliaco','ca'),
	('helíaco', '<span > o ','ca'),
	('helióstato', 'heliostato','<!!special!!>'),
	('helióstato', '<span > o ','<!!special!!>'),
	('hemiplejia', 'hemiplejía','<!!special!!>'),
	('hemiplejia', '<span > o ','<!!special!!>'),
	('hemorroísa', 'hemorroisa','<!!special!!>'),
	('hemorroísa', '<span > o ','<!!special!!>'),
	('heráldico', 'heráldica','ca'),
	('herbolario', 'herbolaria','ria'),
	('herido', 'herida','da'),
	('hermenéutico', 'hermenéutica','ca'),
	('heteromancia', 'heteromancía','<!!special!!>'),
	('heteromancia', '<span > o ','<!!special!!>'),
	('hético', 'hética','ca'),
	('heurístico', 'heurística','ca'),
	('hidráulico', 'hidráulica','ca'),
	('hidrodinámico', 'hidrodinámica','ca'),
	('hidrólisis', 'hidrolisis','<!!special!!>'),
	('hidrólisis', '<span > o ','<!!special!!>'),
	('hidromancia', 'hidromancía','<!!special!!>'),
	('hidromancia', '<span > o ','<!!special!!>'),
	('hidromel', 'hidromiel','<!!special!!>'),
	('hidromel', '<span > o ','<!!special!!>'),
	('higüela', 'higuela','<!!special!!>'),
	('higüela', '<span > o ','<!!special!!>'),
	('hilador', 'hiladora','ra'),
	('hipérbato', 'hipérbaton','<!!special!!>'),
	('hipérbato', '<span > o ','<!!special!!>'),
	('hipercrítico', 'hipercrítica','ca'),
	('hípico', 'hípica','ca'),
	('hipocondríaco', 'hipocondriaco','ca'),
	('hipocondríaco', '<span > o ','ca'),
	('hipomaníaco', 'hipomaniaco','ca'),
	('hipomaníaco', '<span > o ','ca'),
	('hipomoclio', 'hipomoclion','<!!special!!>'),
	('hipomoclio', '<span > o ','<!!special!!>'),
	('holandés', 'holandesa','sa'),
	('huauzontle', 'huazontle','<!!special!!>'),
	('huauzontle', '<span > o ','<!!special!!>'),
	('huesero', 'huesera','ra'),
	('huesudo', 'huesuda','da'),
	('huich', 'huiche','<!!special!!>'),
	('huich', '<span > o ','<!!special!!>'),
	('hulero', 'hulera','ra'),
	('humil', 'húmil','<!!special!!>'),
	('humilmente', 'húmilmente','<!!special!!>'),
	('humilmente', '<span > o ','<!!special!!>'),
	('humil', '<span > o ','<!!special!!>'),
	('humorado', 'humorada','da'),
	('ibero', 'íbero','ra'),
	('ibero', '<span > o ','ra'),
	('icono', 'ícono','<!!special!!>'),
	('icono', '<span > o ','<!!special!!>'),
	('ilercaón', 'ilercavón','na'),
	('ilercaón', '<span > o ','na'),
	('ilíaco', 'iliaco','ca'),
	('ilíaco', '<span > o ','ca'),
	('imperatorio', 'imperatoria','ria'),
	('impío', 'impía','a'),
	('impresor', 'impresora','ra'),
	('incógnito', 'incógnita','ta'),
	('indagatorio', 'indagatoria','ria'),
	('indumentario', 'indumentaria','ria'),
	('infraoctavo', 'infraoctava','va'),
	('iniciativo', 'iniciativa','va'),
	('inmobiliario', 'inmobiliaria','ria'),
	('intelectivo', 'intelectiva','va'),
	('intercolumnio', 'intercolunio','<!!special!!>'),
	('intercolumnio', '<span > o ','<!!special!!>'),
	('in utroque iure', 'in utroque jure','<!!special!!>'),
	('in utroque iure', '<span > o ','<!!special!!>'),
	('inventivo', 'inventiva','va'),
	('inyectador', 'inyectadora','ra'),
	('ion', 'ión','<!!special!!>'),
	('ion', '<span > o ','<!!special!!>'),
	('ipso iure', 'ipso jure','<!!special!!>'),
	('ipso iure', '<span > o ','<!!special!!>'),
	('isiaco', 'isíaco','ca'),
	('isiaco', '<span > o ','ca'),
	('isóbara', 'isobara','<!!special!!>'),
	('isóbara', '<span > o ','<!!special!!>'),
	('isógono', 'isógona','na'),
	('isoquímena', 'isoquimena','<!!special!!>'),
	('isoquímena', '<span > o ','<!!special!!>'),
	('jacarandino', 'jacarandina','na'),
	('jacerino', 'jacerina','na'),
	('jaculatorio', 'jaculatoria','ria'),
	('jeremíaco', 'jeremiaco','ca'),
	('jeremíaco', '<span > o ','ca'),
	('jericalla', 'jericaya','<!!special!!>'),
	('jericalla', '<span > o ','<!!special!!>'),
	('jeroglífico', 'jeroglífica','ca'),
	('jitomatero', 'jitomatera','ra'),
	('jopé', 'jope','<!!special!!>'),
	('jopé', '<span > o ','<!!special!!>'),
	('judaico', 'judaica','ca'),
	('judiciario', 'judiciaria','ria'),
	('kárate', 'karate','<!!special!!>'),
	('kárate', '<span > o ','<!!special!!>'),
	('kílim', 'kilim','<!!special!!>'),
	('kílim', '<span > o ','<!!special!!>'),
	('kohl', 'kohol','<!!special!!>'),
	('kohl', '<span > o ','<!!special!!>'),
	('ladrillero', 'ladrillera','ra'),
	('ladronesco', 'ladronesca','ca'),
	('laminador', 'laminadora','ra'),
	('laminero', 'laminera','ra'),
	('latiguero', 'latiguera','ra'),
	('laudatorio', 'laudatoria','ria'),
	('laureola', 'lauréola','<!!special!!>'),
	('laureola', '<span > o ','<!!special!!>'),
	('lavador', 'lavadora','ra'),
	('lavaloza', 'lavalozas','<!!special!!>'),
	('lavaloza', '<span > o ','<!!special!!>'),
	('lavarropa', 'lavarropas','<!!special!!>'),
	('lavarropa', '<span > o ','<!!special!!>'),
	('lavativo', 'lavativa','va'),
	('lecanomancia', 'lecanomancía','<!!special!!>'),
	('lecanomancia', '<span > o ','<!!special!!>'),
	('lechigado', 'lechigada','da'),
	('lechoso', 'lechosa','sa'),
	('leñero', 'leñera','ra'),
	('leonino', 'leonina','na'),
	('letigio', 'letijo','<!!special!!>'),
	('letigio', '<span > o ','<!!special!!>'),
	('lidón', 'lidonero','<!!special!!>'),
	('lidón', '<span > o ','<!!special!!>'),
	('limonado', 'limonada','da'),
	('limonero', 'limonera','ra'),
	('limosnero', 'limosnera','ra'),
	('lingüístico', 'lingüística','ca'),
	('lipemaniaco', 'lipemaníaco','ca'),
	('lipemaniaco', '<span > o ','ca'),
	('lito-', '-lito','<!!special!!>'),
	('lito-', '<span > o ','<!!special!!>'),
	('lítotes', 'litotes','<!!special!!>'),
	('lítotes', '<span > o ','<!!special!!>'),
	('llegado', 'llegada','da'),
	('locomotor', 'locomotora','ra'),
	('longui', 'longuis','<!!special!!>'),
	('longui', '<span > o ','<!!special!!>'),
	('lucillo', 'lucilo','<!!special!!>'),
	('lucillo', '<span > o ','<!!special!!>'),
	('lustramueble', 'lustramuebles','<!!special!!>'),
	('lustramueble', '<span > o ','<!!special!!>'),
	('machorro', 'machorra','rra'),
	('macrobiótico', 'macrobiótica','ca'),
	('macrocosmo', 'macrocosmos','<!!special!!>'),
	('macrocosmo', '<span > o ','<!!special!!>'),
	('mágico', 'mágica','ca'),
	('mahonés', 'mahonesa','sa'),
	('malagueño', 'malagueña','ña'),
	('malmatado', 'malmatada','da'),
	('mambí', 'mambís','sa'),
	('mambí', '<span > o ','sa'),
	('mampuesto', 'mampuesta','ta'),
	('manchamantel', 'manchamanteles','<!!special!!>'),
	('manchamantel', '<span > o ','<!!special!!>'),
	('-mancia', '-mancía','<!!special!!>'),
	('-mancia', '<span > o ','<!!special!!>'),
	('mándala', 'mandala','<!!special!!>'),
	('mándala', '<span > o ','<!!special!!>'),
	('mandarín', 'mandarina','na'),
	('mandrilador', 'mandriladora','ra'),
	('manganesa', 'manganesia','<!!special!!>'),
	('manganesa', '<span > o ','<!!special!!>'),
	('maníaco', 'maniaco','ca'),
	('maníaco', '<span > o ','ca'),
	('mantecado', 'mantecada','da'),
	('mantenedor', 'mantenedora','ra'),
	('manzanero', 'manzanera','ra'),
	('marcapaso', 'marcapasos','<!!special!!>'),
	('marcapaso', '<span > o ','<!!special!!>'),
	('marcionista', 'marcionita','<!!special!!>'),
	('marcionista', '<span > o ','<!!special!!>'),
	('mariachi', 'mariachis','<!!special!!>'),
	('mariachi', '<span > o ','<!!special!!>'),
	('marinado', 'marinada','da'),
	('maturrango', 'maturranga','ga'),
	('mayéutico', 'mayéutica','ca'),
	('mayúsculo', 'mayúscula','la'),
	('mazorquero', 'mazorquera','ra'),
	('mecateado', 'mecateada','da'),
	('mecedor', 'mecedora','ra'),
	('mechudo', 'mechuda','da'),
	('médula', 'medula','<!!special!!>'),
	('médula', '<span > o ','<!!special!!>'),
	('mejillonero', 'mejillonera','ra'),
	('melado', 'melada','da'),
	('melero', 'melera','ra'),
	('mentado', 'mentada','da'),
	('meón', 'meona','na'),
	('metálico', 'metálica','ca'),
	('metempsícosis', 'metempsicosis','<!!special!!>'),
	('metempsícosis', '<span > o ','<!!special!!>'),
	('meteoro', 'metéoro','<!!special!!>'),
	('meteoro', '<span > o ','<!!special!!>'),
	('metopa', 'métopa','<!!special!!>'),
	('metopa', '<span > o ','<!!special!!>');

INSERT INTO palabra_multigenero (palabra, variante, diferencia) VALUES ('mezclador', 'mezcladora','ra'),
	('mezzoforte', 'mezzo-forte','<!!special!!>'),
	('mezzoforte', '<span > o ','<!!special!!>'),
	('microfilmador', 'microfilmadora','ra'),
	('microscopia', 'microscopía','<!!special!!>'),
	('microscopia', '<span > o ','<!!special!!>'),
	('milanés', 'milanesa','sa'),
	('mildiu', 'mildiú','<!!special!!>'),
	('mildiu', '<span > o ','<!!special!!>'),
	('milésimo', 'milésima','ma'),
	('mímesis', 'mimesis','<!!special!!>'),
	('mímesis', '<span > o ','<!!special!!>'),
	('mímico', 'mímica','ca'),
	('minúsculo', 'minúscula','la'),
	('mirabolano', 'mirabolanos','<!!special!!>'),
	('mirabolano', '<span > o ','<!!special!!>'),
	('mirobálano', 'mirobálanos','<!!special!!>'),
	('mirobálano', '<span > o ','<!!special!!>'),
	('misceláneo', 'miscelánea','a'),
	('mnemónico', 'mnemónica','ca'),
	('mnemotécnico', 'mnemotécnica','ca'),
	('moledero', 'moledera','ra'),
	('moleño', 'moleña','ña'),
	('monitorio', 'monitoria','ria'),
	('monomaníaco', 'monomaniaco','ca'),
	('monomaníaco', '<span > o ','ca'),
	('montador', 'montadora','ra'),
	('mordido', 'mordida','da'),
	('morfo-', '-morfo','fa'),
	('morfo-', '<span > o ','fa'),
	('motero', 'motera','ra'),
	('motorizado', 'motorizada','da'),
	('motor', 'motora','ra'),
	('movido', 'movida','da'),
	('mucilago', 'mucílago','<!!special!!>'),
	('mucilago', '<span > o ','<!!special!!>'),
	('mue', 'mué','<!!special!!>'),
	('mue', '<span > o ','<!!special!!>'),
	('multiuso', 'multiusos','<!!special!!>'),
	('multiuso', '<span > o ','<!!special!!>'),
	('muon', 'muón','<!!special!!>'),
	('muon', '<span > o ','<!!special!!>'),
	('muslim', 'muslime','<!!special!!>'),
	('muslim', '<span > o ','<!!special!!>'),
	('nacido', 'nacida','da'),
	('naíf', 'naif','<!!special!!>'),
	('naíf', '<span > o ','<!!special!!>'),
	('nanche', 'nanchi','<!!special!!>'),
	('nanche', '<span > o ','<!!special!!>'),
	('napolitano', 'napolitana','na'),
	('naranjado', 'naranjada','da'),
	('naranjero', 'naranjera','ra'),
	('narizón', 'narizona','na'),
	('narrativo', 'narrativa','va'),
	('naviero', 'naviera','ra'),
	('necromancia', 'necromancía','<!!special!!>'),
	('necromancia', '<span > o ','<!!special!!>'),
	('negrito', 'negrita','ta'),
	('nemónico', 'nemónica','ca'),
	('nemotécnico', 'nemotécnica','ca'),
	('neroli', 'nerolí','<!!special!!>'),
	('neroli', '<span > o ','<!!special!!>'),
	('neumático', 'neumática','ca'),
	('nigromancia', 'nigromancía','<!!special!!>'),
	('nigromancia', '<span > o ','<!!special!!>'),
	('nomónico', 'nomónica','ca'),
	('novelístico', 'novelística','ca'),
	('nubado', 'nubada','da'),
	('nubarrado', 'nubarrada','da'),
	('numismático', 'numismática','ca'),
	('ñurdo', 'ñurda','da'),
	('ocotero', 'ocotera','ra'),
	('oftalmia', 'oftalmía','<!!special!!>'),
	('oftalmia', '<span > u ','<!!special!!>'),
	('ojalador', 'ojaladora','ra'),
	('ojeado', 'ojeada','da'),
	('olimpiaco', 'olimpíaco','ca'),
	('olimpiaco', '<span > u ','ca'),
	('olimpiada', 'olimpíada','<!!special!!>'),
	('olimpiada', '<span > u ','<!!special!!>'),
	('omóplato', 'omoplato','<!!special!!>'),
	('omóplato', '<span > u ','<!!special!!>'),
	('onicomancia', 'onicomancía','<!!special!!>'),
	('onicomancia', '<span > u ','<!!special!!>'),
	('oniromancia', 'oniromancía','<!!special!!>'),
	('oniromancia', '<span > u ','<!!special!!>'),
	('onomancia', 'onomancía','<!!special!!>'),
	('onomancia', '<span > u ','<!!special!!>'),
	('onomástico', 'onomástica','ca'),
	('opiato', 'opiata','ta'),
	('óptico', 'óptica','ca'),
	('ordeñador', 'ordeñadora','ra'),
	('orfre', 'orfrés','<!!special!!>'),
	('orfre', '<span > u ','<!!special!!>'),
	('orgía', 'orgia','<!!special!!>'),
	('orgía', '<span > u ','<!!special!!>'),
	('ornitomancia', 'ornitomancía','<!!special!!>'),
	('ornitomancia', '<span > u ','<!!special!!>'),
	('orquídeo', 'orquídea','a'),
	('ostrero', 'ostrera','ra'),
	('pabilo', 'pábilo','<!!special!!>'),
	('pabilo', '<span > o ','<!!special!!>'),
	('pachiche', 'pachichi','<!!special!!>'),
	('pachiche', '<span > o ','<!!special!!>'),
	('pachola', 'pacholi','<!!special!!>'),
	('pachola', '<span > o ','<!!special!!>'),
	('pachulí', 'pachuli','<!!special!!>'),
	('pachulí', '<span > o ','<!!special!!>'),
	('pajado', 'pajada','da'),
	('pajarota', 'pajarotada','<!!special!!>'),
	('pajarota', '<span > o ','<!!special!!>'),
	('pajuila', 'pajuilla','<!!special!!>'),
	('pajuila', '<span > o ','<!!special!!>'),
	('palanquero', 'palanquera','ra'),
	('panificador', 'panificadora','ra'),
	('panorámico', 'panorámica','ca'),
	('pañuso', 'pañusa','sa'),
	('papú', 'papúa','<!!special!!>'),
	('papú', '<span > o ','<!!special!!>'),
	('paradisíaco', 'paradisiaco','ca'),
	('paradisíaco', '<span > o ','ca'),
	('paralimpiada', 'paralimpíada','<!!special!!>'),
	('paralimpiada', '<span > o ','<!!special!!>'),
	('paramero', 'paramera','ra'),
	('paraplejia', 'paraplejía','<!!special!!>'),
	('paraplejia', '<span > o ','<!!special!!>'),
	('pardillo', 'pardilla','lla'),
	('parolimpiada', 'parolimpíada','<!!special!!>'),
	('parolimpiada', '<span > o ','<!!special!!>'),
	('parrillero', 'parrillera','ra'),
	('parsec', 'pársec','<!!special!!>'),
	('parsec', '<span > o ','<!!special!!>'),
	('parturienta', 'parturiente','<!!special!!>'),
	('parturienta', '<span > o ','<!!special!!>'),
	('pastor', 'pastora','ra'),
	('pastrano', 'pastrana','na'),
	('patrístico', 'patrística','ca'),
	('patrono', 'patrona','na'),
	('pavonado', 'pavonada','da'),
	('pche', 'pchs','<!!special!!>'),
	('pche', '<span > o ','<!!special!!>'),
	('pecíolo', 'peciolo','<!!special!!>'),
	('pecíolo', '<span > o ','<!!special!!>'),
	('pedorrero', 'pedorrera','ra'),
	('pedrizo', 'pedriza','za'),
	('peinado', 'peinada','da'),
	('peinador', 'peinadora','ra'),
	('peleón', 'peleona','na'),
	('pelícano', 'pelicano','<!!special!!>'),
	('pelícano', '<span > o ','<!!special!!>'),
	('pelón', 'pelona','na'),
	('peloponesiaco', 'peloponesíaco','ca'),
	('peloponesiaco', '<span > o ','ca'),
	('pensil', 'pénsil','<!!special!!>'),
	('pensil', '<span > o ','<!!special!!>'),
	('pentagrama', 'pentágrama','<!!special!!>'),
	('pentagrama', '<span > o ','<!!special!!>'),
	('período', 'periodo','<!!special!!>'),
	('período', '<span > o ','<!!special!!>'),
	('persuasivo', 'persuasiva','va'),
	('peticano', 'peticanon','<!!special!!>'),
	('peticano', '<span > o ','<!!special!!>'),
	('petitorio', 'petitoria','ria'),
	('petroleoquímico', 'petroleoquímica','ca'),
	('petroquímico', 'petroquímica','ca'),
	('picaresco', 'picaresca','ca'),
	('picoso', 'picosa','sa'),
	('pilongo', 'pilonga','ga'),
	('pinolero', 'pinolera','ra'),
	('pion', 'pión','na'),
	('pion', 'pión','<!!special!!>'),
	('pion', '<span > o ','na'),
	('pion', '<span > o ','<!!special!!>'),
	('piromancia', 'piromancía','<!!special!!>'),
	('piromancia', '<span > o ','<!!special!!>'),
	('pisador', 'pisadora','ra'),
	('pistero', 'pistera','ra'),
	('pitayal', 'pitayar','<!!special!!>'),
	('pitayal', '<span > o ','<!!special!!>'),
	('pitorá', 'pitora','<!!special!!>'),
	('pitorá', '<span > o ','<!!special!!>'),
	('píxel', 'pixel','<!!special!!>'),
	('píxel', '<span > o ','<!!special!!>'),
	('platanero', 'platanera','ra'),
	('playero', 'playera','ra'),
	('plim', 'plin','<!!special!!>'),
	('plim', '<span > o ','<!!special!!>'),
	('plumado', 'plumada','da'),
	('podo-', '‒́podo','<!!special!!>'),
	('podo-', '<span > o ','<!!special!!>'),
	('polémico', 'polémica','ca'),
	('policíaco', 'policiaco','ca'),
	('policíaco', '<span > o ','ca'),
	('policromo', 'polícromo','ma'),
	('policromo', '<span > o ','ma'),
	('polígloto', 'poligloto','ta'),
	('polígloto', '<span > o ','ta'),
	('polonés', 'polonesa','sa'),
	('poltrón', 'poltrona','na'),
	('pompi', 'pompis','<!!special!!>'),
	('pompi', '<span > o ','<!!special!!>'),
	('portaequipaje', 'portaequipajes','<!!special!!>'),
	('portaequipaje', '<span > o ','<!!special!!>'),
	('portafolio', 'portafolios','<!!special!!>'),
	('portafolio', '<span > o ','<!!special!!>'),
	('portalámpara', 'portalámparas','<!!special!!>'),
	('portalámpara', '<span > o ','<!!special!!>'),
	('portaobjeto', 'portaobjetos','<!!special!!>'),
	('portaobjeto', '<span > o ','<!!special!!>'),
	('portarretrato', 'portarretratos','<!!special!!>'),
	('portarretrato', '<span > o ','<!!special!!>'),
	('postizo', 'postiza','za'),
	('pragmático', 'pragmática','ca'),
	('premiso', 'premisa','sa'),
	('présago', 'presago','ga'),
	('présago', '<span > o ','ga'),
	('présbita', 'présbite','<!!special!!>'),
	('présbita', '<span > o ','<!!special!!>'),
	('pringado', 'pringada','da'),
	('prion', 'prión','<!!special!!>'),
	('prion', '<span > o ','<!!special!!>'),
	('probatorio', 'probatoria','ria'),
	('procero', 'prócero','ra'),
	('procero', '<span > o ','ra'),
	('productor', 'productora','ra'),
	('profiláctico', 'profiláctica','ca'),
	('propedéutico', 'propedéutica','ca'),
	('prospectivo', 'prospectiva','va'),
	('psicofísico', 'psicofísica','ca'),
	('psicolingüístico', 'psicolingüística','ca'),
	('ptero-', '‒́ptero','ra'),
	('ptero-', '<span > o ','ra'),
	('pucará', 'pucara','<!!special!!>'),
	('pucará', '<span > o ','<!!special!!>'),
	('pudin', 'pudín','<!!special!!>'),
	('pudin', '<span > o ','<!!special!!>'),
	('pulguiento', 'pulguienta','ta'),
	('pulmoníaco', 'pulmoniaco','ca'),
	('pulmoníaco', '<span > o ','ca'),
	('purpurino', 'purpurina','na'),
	('pututo', 'pututu','<!!special!!>'),
	('pututo', '<span > o ','<!!special!!>'),
	('quebrador', 'quebradora','ra'),
	('quebrantador', 'quebrantadora','ra'),
	('quejigal', 'quejigar','<!!special!!>'),
	('quejigal', '<span > o ','<!!special!!>'),
	('quincuagésimo', 'quincuagésima','ma'),
	('quinesioterapia', 'quinesiterapia','<!!special!!>'),
	('quinesioterapia', '<span > o ','<!!special!!>');

INSERT INTO palabra_multigenero (palabra, variante, diferencia) VALUES ('quinesioterápico', 'quinesiterápico','ca'),
	('quinesioterápico', '<span > o ','ca'),
	('quiromancia', 'quiromancía','<!!special!!>'),
	('quiromancia', '<span > o ','<!!special!!>'),
	('quiropráctico', 'quiropráctica','ca'),
	('quitado', 'quitada','da'),
	('rabanero', 'rabanera','ra'),
	('raboseado', 'raboseada','da'),
	('radiodifusor', 'radiodifusora','ra'),
	('ragtime', 'rag-time','<!!special!!>'),
	('ragtime', '<span > o ','<!!special!!>'),
	('raíl', 'rail','<!!special!!>'),
	('raíl', '<span > o ','<!!special!!>'),
	('rancajado', 'rancajada','da'),
	('ranglán', 'ranglan','<!!special!!>'),
	('ranglán', '<span > o ','<!!special!!>'),
	('rascabuchar', 'rascabuchear','<!!special!!>'),
	('rascabuchar', '<span > o ','<!!special!!>'),
	('rasgado', 'rasgada','da'),
	('ratonero', 'ratonera','ra'),
	('recocido', 'recocida','da'),
	('rectificador', 'rectificadora','ra'),
	('refaccionario', 'refaccionaria','ria'),
	('réferi', 'referí','<!!special!!>'),
	('réferi', '<span > o ','<!!special!!>'),
	('refrigerador', 'refrigeradora','ra'),
	('regidoría', 'regiduría','<!!special!!>'),
	('regidoría', '<span > o ','<!!special!!>'),
	('remachador', 'remachadora','ra'),
	('remisorio', 'remisoria','ria'),
	('reostato', 'reóstato','<!!special!!>'),
	('reostato', '<span > o ','<!!special!!>'),
	('repanchigarse', 'repanchingarse','<!!special!!>'),
	('repanchigarse', '<span > o ','<!!special!!>'),
	('repantigarse', 'repantingarse','<!!special!!>'),
	('repantigarse', '<span > o ','<!!special!!>'),
	('reparado', 'reparada','da'),
	('reposero', 'reposera','ra'),
	('reptil', 'réptil','<!!special!!>'),
	('reptil', '<span > o ','<!!special!!>'),
	('resbaladero', 'resbaladera','ra'),
	('resolano', 'resolana','na'),
	('resoli', 'resolí','<!!special!!>'),
	('resoli', '<span > o ','<!!special!!>'),
	('responsivo', 'responsiva','va'),
	('retentivo', 'retentiva','va'),
	('reuma', 'reúma','<!!special!!>'),
	('reuma', '<span > o ','<!!special!!>'),
	('revistero', 'revistera','ra'),
	('revolero', 'revolera','ra'),
	('revolvedor', 'revolvedora','ra'),
	('rezador', 'rezadora','ra'),
	('rezandero', 'rezandera','ra'),
	('rielero', 'rielera','ra'),
	('rizófito', 'rizofito','ta'),
	('rizófito', '<span > o ','ta'),
	('róbalo', 'robalo','<!!special!!>'),
	('róbalo', '<span > o ','<!!special!!>'),
	('rodillero', 'rodillera','ra'),
	('rodrejo', 'rodreja','ja'),
	('rogativo', 'rogativa','va'),
	('rompedero', 'rompedera','ra'),
	('roncador', 'roncadora','ra'),
	('rondeño', 'rondeña','ña'),
	('rosariero', 'rosariera','ra'),
	('rosoli', 'rosolí','<!!special!!>'),
	('rosoli', '<span > o ','<!!special!!>'),
	('rotativo', 'rotativa','va'),
	('rotulador', 'rotuladora','ra'),
	('roturador', 'roturadora','ra'),
	('ruan', 'ruán','<!!special!!>'),
	('ruan', '<span > o ','<!!special!!>'),
	('rubeola', 'rubéola','<!!special!!>'),
	('rubeola', '<span > o ','<!!special!!>'),
	('rufianesco', 'rufianesca','ca'),
	('sabanero', 'sabanera','ra'),
	('sabatino', 'sabatina','na'),
	('saboyano', 'saboyana','na'),
	('sacarino', 'sacarina','na'),
	('sacrismoche', 'sacrismocho','<!!special!!>'),
	('sacrismoche', '<span > o ','<!!special!!>'),
	('saetero', 'saetera','ra'),
	('sahariano', 'sahariana','na'),
	('salamanquino', 'salamanquina','na'),
	('salvajino', 'salvajina','na'),
	('salvapantalla', 'salvapantallas','<!!special!!>'),
	('salvapantalla', '<span > o ','<!!special!!>'),
	('sarracín', 'sarracina','na'),
	('satinador', 'satinadora','ra'),
	('secador', 'secadora','ra'),
	('sedeño', 'sedeña','ña'),
	('segadero', 'segadera','ra'),
	('selen-', 'seleno-','<!!special!!>'),
	('selen-', '<span > o ','<!!special!!>'),
	('semántico', 'semántica','ca'),
	('sembrador', 'sembradora','ra'),
	('semiperíodo', 'semiperiodo','<!!special!!>'),
	('semiperíodo', '<span > o ','<!!special!!>'),
	('sensitivo', 'sensitiva','va'),
	('séptimo', 'séptima','ma'),
	('septuagésimo', 'septuagésima','ma'),
	('serrador', 'serradora','ra'),
	('sicomoro', 'sicómoro','<!!special!!>'),
	('sicomoro', '<span > o ','<!!special!!>'),
	('simoniaco', 'simoníaco','ca'),
	('simoniaco', '<span > o ','ca'),
	('siriaco', 'siríaco','ca'),
	('siriaco', '<span > o ','ca'),
	('sociolingüístico', 'sociolingüística','ca'),
	('sofístico', 'sofística','ca'),
	('soldadesco', 'soldadesca','ca'),
	('solo', 'sólo','<!!special!!>'),
	('solo', '<span > o ','<!!special!!>'),
	('sopero', 'sopera','ra'),
	('sorrapar', 'sorrapear','<!!special!!>'),
	('sorrapar', '<span > o ','<!!special!!>'),
	('sottovoce', 'sotto voce','<!!special!!>'),
	('sottovoce', '<span > o ','<!!special!!>'),
	('sufridero', 'sufridera','ra'),
	('sulfatador', 'sulfatadora','ra'),
	('suplicatorio', 'suplicatoria','ria'),
	('tabarro', '<span > o ','<!!special!!>'),
	('tabarro', 'tábarro','<!!special!!>'),
	('tabulador', 'tabuladora','ra'),
	('taladrador', 'taladradora','ra'),
	('tallado', 'tallada','da'),
	('tangado', 'tangada','da'),
	('tángana', '<span > o ','<!!special!!>'),
	('tángana', 'tangana','<!!special!!>'),
	('tangerino', 'tangerina','na'),
	('tapacubo', '<span > o ','<!!special!!>'),
	('tapacubo', 'tapacubos','<!!special!!>'),
	('taparrabo', '<span > o ','<!!special!!>'),
	('taparrabo', 'taparrabos','<!!special!!>'),
	('taponador', 'taponadora','ra'),
	('tasajero', 'tasajera','ra'),
	('taxón', '<span > o ','<!!special!!>'),
	('taxón', 'taxon','<!!special!!>'),
	('tectónico', 'tectónica','ca'),
	('tecuín', '<span > o ','<!!special!!>'),
	('tecuín', 'tecuino','<!!special!!>'),
	('tejedor', 'tejedora','ra'),
	('telequinesia', '<span > o ','<!!special!!>'),
	('telequinesia', 'telequinesis','<!!special!!>'),
	('temático', 'temática','ca'),
	('tentativo', 'tentativa','va'),
	('teorético', 'teorética','ca'),
	('terapéutico', 'terapéutica','ca'),
	('teredo', '<span > o ','<!!special!!>'),
	('teredo', 'teredón','<!!special!!>'),
	('teresiano', 'teresiana','na'),
	('termodinámico', 'termodinámica','ca'),
	('terrizo', 'terriza','za'),
	('testerillo', 'testerilla','lla'),
	('tetraplejia', '<span > o ','<!!special!!>'),
	('tetraplejia', 'tetraplejía','<!!special!!>'),
	('tifoideo', 'tifoidea','a'),
	('tilichero', 'tilichera','ra'),
	('timonero', 'timonera','ra'),
	('tiritón', 'tiritona','na'),
	('tísico', 'tísica','ca'),
	('tiznero', 'tiznera','ra'),
	('tobillero', 'tobillera','ra'),
	('tomatero', 'tomatera','ra'),
	('topador', 'topadora','ra'),
	('tormentario', 'tormentaria','ria'),
	('tortícolis', '<span > o ','<!!special!!>'),
	('tortícolis', 'torticolis','<!!special!!>'),
	('traído', 'traída','da'),
	('tramontano', 'tramontana','na'),
	('trasero', 'trasera','ra'),
	('trasmontano', 'trasmontana','na'),
	('trasnochado', 'trasnochada','da'),
	('trasplantador', 'trasplantadora','ra'),
	('travesío', 'travesía','a'),
	('travesti', '<span > o ','<!!special!!>'),
	('travesti', 'travestí','<!!special!!>'),
	('travieso', 'traviesa','sa'),
	('tríada', '<span > o ','<!!special!!>'),
	('tríada', 'tríade','<!!special!!>'),
	('triaquero', 'triaquera','ra'),
	('tribada', '<span > o ','<!!special!!>'),
	('tribada', 'tríbada','<!!special!!>'),
	('triglifo', '<span > o ','<!!special!!>'),
	('triglifo', 'tríglifo','<!!special!!>'),
	('triguero', 'triguera','ra'),
	('trillador', 'trilladora','ra'),
	('triturador', 'trituradora','ra'),
	('trochemoche', '<span > o ','<!!special!!>'),
	('trochemoche', 'troche y moche','<!!special!!>'),
	('troica', '<span > o ','<!!special!!>'),
	('troica', 'troika','<!!special!!>'),
	('tronado', 'tronada','da'),
	('true', '<span > o ','<!!special!!>'),
	('true', 'trué','<!!special!!>'),
	('truhan', '<span > o ','na'),
	('truhan', 'truhán','na'),
	('tumbón', 'tumbona','na'),
	('umbrío', 'umbría','a'),
	('uñado', 'uñada','da'),
	('un', 'una','una'),
	('urbanístico', 'urbanística','ca'),
	('uromancia', '<span > o ','<!!special!!>'),
	('uromancia', 'uromancía','<!!special!!>'),
	('valgo', '<span > o ','<!!special!!>'),
	('valgo', 'valgus','<!!special!!>'),
	('valón', 'valona','na'),
	('vaquerizo', 'vaqueriza','za'),
	('varice', '<span > o ','<!!special!!>'),
	('varice', 'várice','<!!special!!>'),
	('varsoviano', 'varsoviana','na'),
	('veintiuno', 'veintiuna','na'),
	('velador', 'veladora','ra'),
	('velís', 'veliz','<!!special!!>'),
	('velonero', 'velonera','ra'),
	('veranero', 'veranera','ra'),
	('verdeceladón', '<span > o ','<!!special!!>'),
	('verdeceladón', 'verdeceledón','<!!special!!>'),
	('vermú', '<span > o ','<!!special!!>'),
	('vermú', 'vermut','<!!special!!>'),
	('veterinario', 'veterinaria','ria'),
	('villanesco', 'villanesca','ca'),
	('virado', 'virada','da'),
	('visitador', 'visitadora','ra'),
	('vitrocerámico', 'vitrocerámica','ca'),
	('voladero', 'voladera','ra'),
	('volador', 'voladora','ra'),
	('volandero', 'volandera','ra'),
	('vómico', 'vómica','ca'),
	('vuelacerca', '<span > o ','<!!special!!>'),
	('vuelacerca', 'vuelacercas','<!!special!!>'),
	('windsurfing', '<span > o ','<!!special!!>'),
	('windsurfing', 'wind surfing','<!!special!!>'),
	('windsurf', '<span > o ','<!!special!!>'),
	('windsurf', 'wind surf','<!!special!!>'),
	('xeroftalmia', '<span > o ','<!!special!!>'),
	('xeroftalmia', 'xeroftalmía','<!!special!!>'),
	('yérsey', '<span > o ','<!!special!!>'),
	('yérsey', 'yersi','<!!special!!>'),
	('yóquey', '<span > o ','<!!special!!>'),
	('yóquey', 'yoqui','<!!special!!>'),
	('yusero', 'yusera','ra'),
	('zafado', 'zafada','da'),
	('zafirino', 'zafirina','na'),
	('zaguero', 'zaguera','ra'),
	('zatico', '<span > o ','<!!special!!>'),
	('zatico', 'zatillo','<!!special!!>'),
	('zodiaco', '<span > o ','<!!special!!>'),
	('zodiaco', 'zodíaco','<!!special!!>');

INSERT INTO palabra_multigenero (palabra, variante, diferencia) VALUES ('zoo-', '<span > o ','<!!special!!>'),
	('zoo-', '-zoo','<!!special!!>'),
	('zumacal', '<span > o ','<!!special!!>'),
	('zumacal', 'zumacar','<!!special!!>'),
	('zumbador', 'zumbadora','ra'),
	('zurito', 'zurita','ta');
