INSERT variante VALUE('*acifolium,','*acifŭlum,');
INSERT variante VALUE('acrostique','acrostiche');
INSERT variante VALUE('-acŭlus','-atĭcus');
INSERT variante VALUE('aḍḍíman','aḍḍamán,');
INSERT variante VALUE('addukkán','addukkín,');
INSERT variante VALUE('*ad iḥála','*et iḥála');
INSERT variante VALUE('aeque sic,','ad sic');
INSERT variante VALUE('aerarĭus','aerarĭum');
INSERT variante VALUE('afeitar','<a title="leonés o leonesa">leon.</a> afeitar,');
INSERT variante VALUE('alaṭríyya','aliṭríyya');
INSERT variante VALUE('alcohol','fenol');
INSERT variante VALUE('alẖánǧar','alẖánǧal,');
INSERT variante VALUE('alkirá','alkirí,');
INSERT variante VALUE('alkisá','alkisí,');
INSERT variante VALUE('alma‘dán','alma‘dín,');
INSERT variante VALUE('almaḥálla','almuḥálla,');
INSERT variante VALUE('almalḥáfa','almaláḥfa,');
INSERT variante VALUE('almártaq','almártak');
INSERT variante VALUE('almihrás','almihráz,');
INSERT variante VALUE('almozala','almozalla');
INSERT variante VALUE('alqarṭás','alqirṭás');
INSERT variante VALUE('alqiṭrán','alqaṭrán');
INSERT variante VALUE('*ált amínk[o]','*ált amánk[o]');
INSERT variante VALUE('anca','<a title="provenzal">prov.</a> anca');
INSERT variante VALUE('ancorel','<a title="catalán o catalana">cat.</a> ancorell,');
INSERT variante VALUE('anníl','annír');
INSERT variante VALUE('annušaṭar','annušaṭir');
INSERT variante VALUE('aohuicate','avoka');
INSERT variante VALUE('argén','<a title="catalán o catalana">cat.</a> argent');
INSERT variante VALUE('argue','<a title="provenzal">prov.</a> argue');
INSERT variante VALUE('Aristocrătes','Democrătes');
INSERT variante VALUE('arrhae','arrhăbo');
INSERT variante VALUE('āruz[z]','aruz[z],');
INSERT variante VALUE('aššaṭranǧ','aššiṭranǧ');
INSERT variante VALUE('aššaṭríyya','aššiṭríyya,');
INSERT variante VALUE('*assediāre','*assedāre');
INSERT variante VALUE('aššiwár','aššuwár,');
INSERT variante VALUE('assúnbar','assúnbal,');
INSERT variante VALUE('*atamiz','*altamiz');
INSERT variante VALUE('<a title="árabe">ár.</a> <a title="hispánico">hisp.</a> almatríǧ','almatríč');
INSERT variante VALUE('atole','atol');
INSERT variante VALUE('aṭṭabbáqa','aṭṭubbáqa,');
INSERT variante VALUE('attamyíz','attamíz');
INSERT variante VALUE('-atūs','-ātum');
INSERT variante VALUE('baco,','bacco');
INSERT variante VALUE('balá','balí');
INSERT variante VALUE('*bálago-','*bálaco-');
INSERT variante VALUE('bayṭar','bayṭār,');
INSERT variante VALUE('bel','<a title="catalán o catalana">cat.</a> bell');
INSERT variante VALUE('Bernia,','Hibernia');
INSERT variante VALUE('*betūle','*betūlus');
INSERT variante VALUE('birlo','birlar');
INSERT variante VALUE('bonavoglia','buonavoglia');
INSERT variante VALUE('bordell','<a title="provenzal">prov.</a> bordel');
INSERT variante VALUE('botchí','<a title="catalán o catalana">cat.</a> botxí');
INSERT variante VALUE('burnús','barnús');
INSERT variante VALUE('calpolli','calpulli');
INSERT variante VALUE('*cassus','*cassinus');
INSERT variante VALUE('centli','cintli');
INSERT variante VALUE('cerifolio','cerfollo');
INSERT variante VALUE('chagra,','chacra');
INSERT variante VALUE('chapapote','<a>caribe</a>');
INSERT variante VALUE('cherŭbim','cherŭbin,');
INSERT variante VALUE('chia','chian');
INSERT variante VALUE('choza','<a title="portugués o portuguesa">port.</a> choza');
INSERT variante VALUE('clan','clamp,');
INSERT variante VALUE('*combŏrtia','*combrŏttia,');
INSERT variante VALUE('condrila','χονδρίλη');
INSERT variante VALUE('conthi','conthùl');
INSERT variante VALUE('cors','cohors');
INSERT variante VALUE('corvatta','crovatta');
INSERT variante VALUE('costa','<a title="catalán o catalana">cat.</a> costa');
INSERT variante VALUE('‒́crata','-κράτης');
INSERT variante VALUE('daucum','daucos,');
INSERT variante VALUE('desbullar','<a title="leonés o leonesa">leon.</a> esbulhar');
INSERT variante VALUE('devanagari','<a title="inglés o inglesa">ingl.</a> devanagari,');
INSERT variante VALUE('disciplinar','disciplinarse');
INSERT variante VALUE('dis-','di-');
INSERT variante VALUE('dolband','dulband,');
INSERT variante VALUE('embarazar','<a title="leonés o leonesa">leon.</a> embaraçar');
INSERT variante VALUE('embicar','<a title="portugués o portuguesa">port.</a> bico');
INSERT variante VALUE('escamel','<a title="catalán o catalana">cat.</a> scamell,');
INSERT variante VALUE('espiche','espicho');
INSERT variante VALUE('Faetón','Faetonte');
INSERT variante VALUE('*farfál','*farfár,');
INSERT variante VALUE('farrūǧ','furrūǧ');
INSERT variante VALUE('Fernambuco,','Pernambuco');
INSERT variante VALUE('fugāre','fugĕre');
INSERT variante VALUE('furnia','<a title="portugués o portuguesa">port.</a> furna');
INSERT variante VALUE('gabila','gabala');
INSERT variante VALUE('ǧahăz','ǧihăz');
INSERT variante VALUE('ḡalālah','ḡilālah');
INSERT variante VALUE('ganacha','garnacha');
INSERT variante VALUE('ḡarab[a]','yaḡrub[u]');
INSERT variante VALUE('gargaridiāre','-zāre');
INSERT variante VALUE('ḡarnáṭi','iḡranáti');
INSERT variante VALUE('ǧaṣṣ','ǧiṣṣ');
INSERT variante VALUE('gaz','kaž');
INSERT variante VALUE('gorgez','gurgez');
INSERT variante VALUE('gruta','<a>siciliano</a> grutta');
INSERT variante VALUE('gúa','guara');
INSERT variante VALUE('guelte','<a title="alemán o alemana">al.</a> geld');
INSERT variante VALUE('gummi','cummi,');
INSERT variante VALUE('*haḏḏúra','*haḏúrra,');
INSERT variante VALUE('hadrolla','fadrolla');
INSERT variante VALUE('ẖalanǧān','ẖūlanǧān');
INSERT variante VALUE('ḥarḍún','ḥarḏún,');
INSERT variante VALUE('harpar','farpar,');
INSERT variante VALUE('ẖarrūbah','ẖarnūbah,');
INSERT variante VALUE('ẖazz','qazz,');
INSERT variante VALUE('healmet','<a title="catalán o catalana">cat.</a> elmet');
INSERT variante VALUE('hinnitŭlus','hinnītus');
INSERT variante VALUE('hippie','hippy');
INSERT variante VALUE('{ht}','{dr}');
INSERT variante VALUE('-ĭdus,','-ĕus');
INSERT variante VALUE('ihiotl','ihiyotl');
INSERT variante VALUE('-īnus','-ĭnus');
INSERT variante VALUE('isbānaẖ','isfānaẖ,');
INSERT variante VALUE('-īta','-ītes,');
INSERT variante VALUE('italianizar','italianizarse');
INSERT variante VALUE('-itĭus','-icĭus');
INSERT variante VALUE('iṯmid','uṯmud,');
INSERT variante VALUE('ĭum,','-ĭdus,');
INSERT variante VALUE('-ĭus,','ĭum,');
INSERT variante VALUE('jàssera','jàssena,');
INSERT variante VALUE('jerpa','serpa');
INSERT variante VALUE('julbána','jilbána,');
INSERT variante VALUE('kelembak','kelambak');
INSERT variante VALUE('kinúwa','kínua');
INSERT variante VALUE('*kórčo','*kórče,');
INSERT variante VALUE('korónta','qurunta');
INSERT variante VALUE('laǧvard','lažvard,');
INSERT variante VALUE('laucha','llaucha');
INSERT variante VALUE('lila[n]ǧ','lilang,');
INSERT variante VALUE('linhatge','<a title="catalán o catalana">cat.</a> llinyatge');
INSERT variante VALUE('-lisis','‒́lisis');
INSERT variante VALUE('Loanda','San Pablo de Loanda');
INSERT variante VALUE('maia','maea,');
INSERT variante VALUE('makito','maketo');
INSERT variante VALUE('manatí','<a>arahuaca</a>');
INSERT variante VALUE('-mancia','-mancía');
INSERT variante VALUE('mandīl','mindīl');
INSERT variante VALUE('mangle','<a>arahuaca</a>');
INSERT variante VALUE('mantīle','mantēle');
INSERT variante VALUE('martak','mortak');
INSERT variante VALUE('masúrqa','maṣúrqa');
INSERT variante VALUE('menge','<a title="provenzal">prov.</a> menge');
INSERT variante VALUE('mermellique','*margarique');
INSERT variante VALUE('mesmo','mismo');
INSERT variante VALUE('mespĭlus','mespĭlum,');
INSERT variante VALUE('métal,','<a title="catalán o catalana">cat.</a> metall');
INSERT variante VALUE('mẖālṭa','mūẖālāṭa');
INSERT variante VALUE('moccobello','<a title="catalán o catalana">cat.</a> mogobells');
INSERT variante VALUE('molli','mulli');
INSERT variante VALUE('monção','moução');
INSERT variante VALUE('morel de sal','<a title="provenzal">prov.</a>');
INSERT variante VALUE('morocoto','morrocoto');
INSERT variante VALUE('mosolmān','moslemān');
INSERT variante VALUE('mote','<a title="francés o francesa">fr.</a> mot');
INSERT variante VALUE('*muharráǧ','*muharríǧ,');
INSERT variante VALUE('nacra','nacre,');
INSERT variante VALUE('nârikela','nârikera');
INSERT variante VALUE('naucŭla','navicūla');
INSERT variante VALUE('neto','<a title="francés o francesa">fr.</a> net');
INSERT variante VALUE('nocchio','gnocco');
INSERT variante VALUE('novālis','novāle');
INSERT variante VALUE('nušādir','nūšādir');
INSERT variante VALUE('ollar','<a title="portugués o portuguesa">port.</a> ollo');
INSERT variante VALUE('ottomano','<a title="francés o francesa">fr.</a> ottoman');
INSERT variante VALUE('palqa','pallqa');
INSERT variante VALUE('pargār','pargāl');
INSERT variante VALUE('par,','por');
INSERT variante VALUE('Parsi','Parsee');
INSERT variante VALUE('péage,','<a title="catalán o catalana">cat.</a> peatge');
INSERT variante VALUE('Pelendōnes','Pellendōnes');
INSERT variante VALUE('pendanga','pindonga');
INSERT variante VALUE('pendón','<a title="provenzal">prov.</a> penon');
INSERT variante VALUE('Pere','Pérez');
INSERT variante VALUE('pesquisar','pescar');
INSERT variante VALUE('pian','<a title="guaraní">guar.</a>');
INSERT variante VALUE('pichel','<a title="francés o francesa">fr.</a> pichier');
INSERT variante VALUE('prensāre','prehensāre');
INSERT variante VALUE('prunum','prunus');
INSERT variante VALUE('prunus,','prunum');
INSERT variante VALUE('punto','punta');
INSERT variante VALUE('qālab','qālib,');
INSERT variante VALUE('qālab','qālib');
INSERT variante VALUE('qarqā','qurqā');
INSERT variante VALUE('qesṭā','qisṭā,');
INSERT variante VALUE('qubṭiyyah','qibṭiyyah');
INSERT variante VALUE('quermes','carmesí');
INSERT variante VALUE('qurṭum','qirṭim');
INSERT variante VALUE('racchetta','<a title="francés o francesa">fr.</a> raquette');
INSERT variante VALUE('rampa','<a>franco</a> *kramp');
INSERT variante VALUE('raṭl','riṭl,');
INSERT variante VALUE('redarmāre','rearmāre');
INSERT variante VALUE('retrete','<a title="catalán o catalana">cat.</a> retret');
INSERT variante VALUE('risico','rischio,');
INSERT variante VALUE('rodandărum','lorandrum');
INSERT variante VALUE('roquete','<a title="provenzal">prov.</a> roquet');
INSERT variante VALUE('rūpya','rūpaka');
INSERT variante VALUE('ṣadāq','ṣidāq');
INSERT variante VALUE('sahríǧ','ṣahríǧ');
INSERT variante VALUE('saḥūr','suḥūr');
INSERT variante VALUE('sain','tzai');
INSERT variante VALUE('šamsíyya','*šamisíyya');
INSERT variante VALUE('sarbāl[ā]','sarbēlā');
INSERT variante VALUE('sarbēlā','sarbalā');
INSERT variante VALUE('sastre','<a title="catalán o catalana">cat.</a> sartre');
INSERT variante VALUE('šawār','šiwār');
INSERT variante VALUE('schote','schoot');
INSERT variante VALUE('Scottus','Scotus');
INSERT variante VALUE('seinsaín','seintzai');
INSERT variante VALUE('šífra','šáfra,');
INSERT variante VALUE('silleta','sillete');
INSERT variante VALUE('sinabafa','sinabafo,');
INSERT variante VALUE('*ṣiqál','siqál,');
INSERT variante VALUE('ṣirāṭ','sirāṭ');
INSERT variante VALUE('sollado','<a title="portugués o portuguesa">port.</a> sollado,');
INSERT variante VALUE('sucre glace','glacé');
INSERT variante VALUE('sullah','sillah,');
INSERT variante VALUE('súrra','ṣúrra,');
INSERT variante VALUE('tafetán','<a title="italiano o italiana">it.</a> taffeta');
INSERT variante VALUE('ṭála‘','ṭáli‘,');
INSERT variante VALUE('talent scout','headhunter');
INSERT variante VALUE('tar angabin','tar angobin');
INSERT variante VALUE('tararira','<a title="guaraní">guar.</a>');
INSERT variante VALUE('targamānu[m]','turgamānu[m]');
INSERT variante VALUE('ṭarkon','ṭarẖon,');
INSERT variante VALUE('ṭassah','ṭast,');
INSERT variante VALUE('tenik','čenik');
INSERT variante VALUE('teocentli','teoxintli');
INSERT variante VALUE('teotl','teutl');
INSERT variante VALUE('tiramisu','tirami su,');
INSERT variante VALUE('tola','tula');
INSERT variante VALUE('trapētum','trapētus');
INSERT variante VALUE('traste','trasto');
INSERT variante VALUE('ṭūrah','ṭuwarah');
INSERT variante VALUE('‘urúq sús','‘írq sús,');
INSERT variante VALUE('yampa','<a>caribe</a>');
INSERT variante VALUE('zanca','tzanga,');
INSERT variante VALUE('zarāfah','zurāfah');
INSERT variante VALUE('zāwq','zā"ūq,');
INSERT variante VALUE('zurāfah','zarāfah');
INSERT variante VALUE('ἐγώ','<a title="latín');
INSERT variante VALUE('γαμετή','γαμέτης');
INSERT variante VALUE('δαῦκος','δαῦκον');
INSERT variante VALUE('οἰνοδήεας','ὀνοδήεας');
