USE drae;

INSERT INTO variante VALUE('*acifolium,','*acifŭlum,'),
	('acrostique','acrostiche'),
	('-acŭlus','-atĭcus'),
	('aḍḍíman','aḍḍamán,'),
	('addukkán','addukkín,'),
	('*ad iḥála','*et iḥála'),
	('aeque sic,','ad sic'),
	('aerarĭus','aerarĭum'),
	('afeitar','<a title="leonés o leonesa">leon.</a> afeitar,'),
	('alaṭríyya','aliṭríyya'),
	('alcohol','fenol'),
	('alẖánǧar','alẖánǧal,'),
	('alkirá','alkirí,'),
	('alkisá','alkisí,'),
	('alma‘dán','alma‘dín,'),
	('almaḥálla','almuḥálla,'),
	('almalḥáfa','almaláḥfa,'),
	('almártaq','almártak'),
	('almihrás','almihráz,'),
	('almozala','almozalla'),
	('alqarṭás','alqirṭás'),
	('alqiṭrán','alqaṭrán'),
	('*ált amínk[o]','*ált amánk[o]'),
	('anca','<a title="provenzal">prov.</a> anca'),
	('ancorel','<a title="catalán o catalana">cat.</a> ancorell,'),
	('anníl','annír'),
	('annušaṭar','annušaṭir'),
	('aohuicate','avoka'),
	('argén','<a title="catalán o catalana">cat.</a> argent'),
	('argue','<a title="provenzal">prov.</a> argue'),
	('Aristocrătes','Democrătes'),
	('arrhae','arrhăbo'),
	('āruz[z]','aruz[z],'),
	('aššaṭranǧ','aššiṭranǧ'),
	('aššaṭríyya','aššiṭríyya,'),
	('*assediāre','*assedāre'),
	('aššiwár','aššuwár,'),
	('assúnbar','assúnbal,'),
	('*atamiz','*altamiz'),
	('<a title="árabe">ár.</a> <a title="hispánico">hisp.</a> almatríǧ','almatríč'),
	('atole','atol'),
	('aṭṭabbáqa','aṭṭubbáqa,'),
	('attamyíz','attamíz'),
	('-atūs','-ātum'),
	('baco,','bacco'),
	('balá','balí'),
	('*bálago-','*bálaco-'),
	('bayṭar','bayṭār,'),
	('bel','<a title="catalán o catalana">cat.</a> bell'),
	('Bernia,','Hibernia'),
	('*betūle','*betūlus'),
	('birlo','birlar'),
	('bonavoglia','buonavoglia'),
	('bordell','<a title="provenzal">prov.</a> bordel'),
	('botchí','<a title="catalán o catalana">cat.</a> botxí'),
	('burnús','barnús'),
	('calpolli','calpulli'),
	('*cassus','*cassinus'),
	('centli','cintli'),
	('cerifolio','cerfollo'),
	('chagra,','chacra'),
	('chapapote','<a>caribe</a>'),
	('cherŭbim','cherŭbin,'),
	('chia','chian'),
	('choza','<a title="portugués o portuguesa">port.</a> choza'),
	('clan','clamp,'),
	('*combŏrtia','*combrŏttia,'),
	('condrila','χονδρίλη'),
	('conthi','conthùl'),
	('cors','cohors'),
	('corvatta','crovatta'),
	('costa','<a title="catalán o catalana">cat.</a> costa'),
	('‒́crata','-κράτης'),
	('daucum','daucos,'),
	('desbullar','<a title="leonés o leonesa">leon.</a> esbulhar'),
	('devanagari','<a title="inglés o inglesa">ingl.</a> devanagari,'),
	('disciplinar','disciplinarse'),
	('dis-','di-'),
	('dolband','dulband,'),
	('embarazar','<a title="leonés o leonesa">leon.</a> embaraçar'),
	('embicar','<a title="portugués o portuguesa">port.</a> bico'),
	('escamel','<a title="catalán o catalana">cat.</a> scamell,'),
	('espiche','espicho'),
	('Faetón','Faetonte'),
	('*farfál','*farfár,'),
	('farrūǧ','furrūǧ'),
	('Fernambuco,','Pernambuco'),
	('fugāre','fugĕre'),
	('furnia','<a title="portugués o portuguesa">port.</a> furna'),
	('gabila','gabala'),
	('ǧahăz','ǧihăz'),
	('ḡalālah','ḡilālah'),
	('ganacha','garnacha'),
	('ḡarab[a]','yaḡrub[u]'),
	('gargaridiāre','-zāre'),
	('ḡarnáṭi','iḡranáti'),
	('ǧaṣṣ','ǧiṣṣ'),
	('gaz','kaž'),
	('gorgez','gurgez'),
	('gruta','<a>siciliano</a> grutta'),
	('gúa','guara'),
	('guelte','<a title="alemán o alemana">al.</a> geld'),
	('gummi','cummi,'),
	('*haḏḏúra','*haḏúrra,'),
	('hadrolla','fadrolla'),
	('ẖalanǧān','ẖūlanǧān'),
	('ḥarḍún','ḥarḏún,'),
	('harpar','farpar,'),
	('ẖarrūbah','ẖarnūbah,'),
	('ẖazz','qazz,'),
	('healmet','<a title="catalán o catalana">cat.</a> elmet'),
	('hinnitŭlus','hinnītus'),
	('hippie','hippy'),
	('{ht}','{dr}'),
	('-ĭdus,','-ĕus'),
	('ihiotl','ihiyotl'),
	('-īnus','-ĭnus'),
	('isbānaẖ','isfānaẖ,'),
	('-īta','-ītes,'),
	('italianizar','italianizarse'),
	('-itĭus','-icĭus'),
	('iṯmid','uṯmud,'),
	('ĭum,','-ĭdus,'),
	('-ĭus,','ĭum,'),
	('jàssera','jàssena,'),
	('jerpa','serpa'),
	('julbána','jilbána,'),
	('kelembak','kelambak'),
	('kinúwa','kínua'),
	('*kórčo','*kórče,'),
	('korónta','qurunta'),
	('laǧvard','lažvard,'),
	('laucha','llaucha'),
	('lila[n]ǧ','lilang,'),
	('linhatge','<a title="catalán o catalana">cat.</a> llinyatge'),
	('-lisis','‒́lisis'),
	('Loanda','San Pablo de Loanda'),
	('maia','maea,'),
	('makito','maketo'),
	('manatí','<a>arahuaca</a>'),
	('-mancia','-mancía'),
	('mandīl','mindīl'),
	('mangle','<a>arahuaca</a>'),
	('mantīle','mantēle'),
	('martak','mortak'),
	('masúrqa','maṣúrqa'),
	('menge','<a title="provenzal">prov.</a> menge'),
	('mermellique','*margarique'),
	('mesmo','mismo'),
	('mespĭlus','mespĭlum,'),
	('métal,','<a title="catalán o catalana">cat.</a> metall'),
	('mẖālṭa','mūẖālāṭa'),
	('moccobello','<a title="catalán o catalana">cat.</a> mogobells'),
	('molli','mulli'),
	('monção','moução'),
	('morel de sal','<a title="provenzal">prov.</a>'),
	('morocoto','morrocoto'),
	('mosolmān','moslemān'),
	('mote','<a title="francés o francesa">fr.</a> mot'),
	('*muharráǧ','*muharríǧ,'),
	('nacra','nacre,'),
	('nârikela','nârikera'),
	('naucŭla','navicūla'),
	('neto','<a title="francés o francesa">fr.</a> net'),
	('nocchio','gnocco'),
	('novālis','novāle'),
	('nušādir','nūšādir'),
	('ollar','<a title="portugués o portuguesa">port.</a> ollo'),
	('ottomano','<a title="francés o francesa">fr.</a> ottoman'),
	('palqa','pallqa'),
	('pargār','pargāl'),
	('par,','por'),
	('Parsi','Parsee'),
	('péage,','<a title="catalán o catalana">cat.</a> peatge'),
	('Pelendōnes','Pellendōnes'),
	('pendanga','pindonga'),
	('pendón','<a title="provenzal">prov.</a> penon'),
	('Pere','Pérez'),
	('pesquisar','pescar'),
	('pian','<a title="guaraní">guar.</a>'),
	('pichel','<a title="francés o francesa">fr.</a> pichier'),
	('prensāre','prehensāre'),
	('prunum','prunus'),
	('prunus,','prunum'),
	('punto','punta'),
	('qālab','qālib,'),
	('qālab','qālib'),
	('qarqā','qurqā'),
	('qesṭā','qisṭā,'),
	('qubṭiyyah','qibṭiyyah'),
	('quermes','carmesí'),
	('qurṭum','qirṭim'),
	('racchetta','<a title="francés o francesa">fr.</a> raquette'),
	('rampa','<a>franco</a> *kramp'),
	('raṭl','riṭl,'),
	('redarmāre','rearmāre'),
	('retrete','<a title="catalán o catalana">cat.</a> retret'),
	('risico','rischio,'),
	('rodandărum','lorandrum'),
	('roquete','<a title="provenzal">prov.</a> roquet'),
	('rūpya','rūpaka'),
	('ṣadāq','ṣidāq'),
	('sahríǧ','ṣahríǧ'),
	('saḥūr','suḥūr'),
	('sain','tzai'),
	('šamsíyya','*šamisíyya'),
	('sarbāl[ā]','sarbēlā'),
	('sarbēlā','sarbalā'),
	('sastre','<a title="catalán o catalana">cat.</a> sartre'),
	('šawār','šiwār'),
	('schote','schoot'),
	('Scottus','Scotus'),
	('seinsaín','seintzai'),
	('šífra','šáfra,'),
	('silleta','sillete'),
	('sinabafa','sinabafo,'),
	('*ṣiqál','siqál,'),
	('ṣirāṭ','sirāṭ'),
	('sollado','<a title="portugués o portuguesa">port.</a> sollado,'),
	('sucre glace','glacé'),
	('sullah','sillah,'),
	('súrra','ṣúrra,'),
	('tafetán','<a title="italiano o italiana">it.</a> taffeta'),
	('ṭála‘','ṭáli‘,'),
	('talent scout','headhunter'),
	('tar angabin','tar angobin'),
	('tararira','<a title="guaraní">guar.</a>'),
	('targamānu[m]','turgamānu[m]'),
	('ṭarkon','ṭarẖon,'),
	('ṭassah','ṭast,'),
	('tenik','čenik'),
	('teocentli','teoxintli'),
	('teotl','teutl'),
	('tiramisu','tirami su,'),
	('tola','tula'),
	('trapētum','trapētus'),
	('traste','trasto'),
	('ṭūrah','ṭuwarah'),
	('‘urúq sús','‘írq sús,'),
	('yampa','<a>caribe</a>'),
	('zanca','tzanga,'),
	('zarāfah','zurāfah'),
	('zāwq','zā"ūq,'),
	('zurāfah','zarāfah'),
	('ἐγώ','<a title="latín'),
	('γαμετή','γαμέτης'),
	('δαῦκος','δαῦκον'),
	('οἰνοδήεας','ὀνοδήεας');
